homeassistant:
  customize:
    sensor.kitchen_echo_one_nmap_tracker:
      friendly_name: "Kitchen Echo"
      icon: mdi:amazon

sensor:
  - platform: template
    sensors:
      kitchen_echo_one_nmap_tracker:
        value_template: "{%if states.device_tracker.kitchen_echo_one.state == 'home'%}Online{%else%}Offline{%endif%}"