##########################################
########## System Automations ############
##########################################
- id: on_start_event
  alias: on_start_event
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:01:00'
    - service: script.turn_on
      entity_id: script.correct_objects_values
    - service: script.turn_on
      entity_id: script.run_speed_test
    - service: script.turn_on
      entity_id: script.get_workstation_mqtt_client_status
    - service: script.turn_on
      entity_id: script.check_last_recorder_session

- id: set_log_level
  alias: set_log_level
  trigger:
    platform: state
    entity_id: input_select.select_log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"

##########################################
#### Office Ceiling Fan Automations ######
##########################################
- id: office_fan_level_change_on
  alias: office_fan_level_change_on
  trigger:
    platform: state
    entity_id: input_select.office_ceiling_fan_level
    from: "OFF_"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.office_light
    - service: switch.turn_on
      data_template:
        entity_id: >
          {%if trigger.to_state.state == "LOW"%}switch.office_fan_low_speed
          {%elif trigger.to_state.state == "MED"%}switch.office_fan_medium_speed
          {%elif trigger.to_state.state == "HIGH"%}switch.office_fan_high_speed
          {%else%}switch.office_fan
          {%endif%}

- id: office_fan_level_change_off
  alias: office_fan_level_change_off
  trigger:
    platform: state
    entity_id: input_select.office_ceiling_fan_level
    to: "OFF_"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.office_fan

- id: office_light_off
  alias: office_light_off
  trigger:
    platform: state
    entity_id: switch.office_light
    to: 'off'
  action:
    - service: python_script.set_entity_state
      data:
        state: 'OFF_'
        entity_id: input_select.office_ceiling_fan_level
    - service: python_script.set_entity_state
      data:
        state: 'off'
        entity_id:
        - switch.office_fan_light
        - switch.office_fan_low_speed
        - switch.office_fan_medium_speed
        - switch.office_fan_high_speed
        - switch.office_fan

- id: office_light_on
  alias: office_light_on
  trigger:
    platform: state
    entity_id: switch.office_light
    to: 'on'
  action:
    service: python_script.set_entity_state
    data:
      state: 'on'
      entity_id: switch.office_fan_light

- id: office_fan_off
  alias: office_fan_off
  trigger:
    - platform: state
      entity_id: switch.office_fan_low_speed
      to: 'off'
    - platform: state
      entity_id: switch.office_fan_medium_speed
      to: 'off'
    - platform: state
      entity_id: switch.office_fan_high_speed
      to: 'off'
    - platform: state
      entity_id: switch.office_fan
      to: 'off'
  action:
    - service: python_script.set_entity_state
      data:
        state: 'off'
        entity_id:
          - switch.office_fan_low_speed
          - switch.office_fan_medium_speed
          - switch.office_fan_high_speed
          - switch.office_fan
    - service: python_script.set_entity_state
      data:
        state: 'OFF_'
        entity_id: input_select.office_ceiling_fan_level

- id: office_fan_on
  alias: office_fan_on
  trigger:
    - platform: state
      entity_id: switch.office_fan_low_speed
      to: 'on'
    - platform: state
      entity_id: switch.office_fan_medium_speed
      to: 'on'
    - platform: state
      entity_id: switch.office_fan_high_speed
      to: 'on'
    - platform: state
      entity_id: switch.office_fan
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.office_light
    - service: input_select.select_option
      data_template:
        entity_id: input_select.office_ceiling_fan_level
        option: >
          {%if trigger.entity_id == "switch.office_fan_low_speed" %}LOW
          {%elif trigger.entity_id == "switch.office_fan_medium_speed" %}MED
          {%elif trigger.entity_id == "switch.office_fan_high_speed" %}HIGH
          {%else%}OFF_
          {%endif%}

- id: office_fan_light_on
  alias: office_fan_light_on
  trigger:
    platform: state
    entity_id: switch.office_fan_light
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.office_light

###########################################
######### Tracking Automations ############
###########################################
- id: update_hava_last_state
  alias: update_hava_last_state
  trigger:
    - platform: state
      entity_id: device_tracker.havaphone_hpowntracks
  action:
    service: input_text.set_value
    data_template:
      entity_id: input_text.hava_last_state
      value: >
        {% if trigger.to_state.state == 'not_home' %}
          {{ states.sensor.hava_owntracks_gecode.state }}
        {%else%}{{ trigger.to_state.state | title }}
        {%endif%}

- id: update_tomer_last_state
  alias: update_tomer_last_state
  trigger:
    - platform: state
      entity_id: device_tracker.tomerphone_tpowntracks
  action:
    service: input_text.set_value
    data_template:
      entity_id: input_text.tomer_last_state
      value: >
        {% if trigger.to_state.state == 'not_home' %}
          {{ states.sensor.tomer_owntracks_gecode.state }}
        {%else%}{{ trigger.to_state.state | title }}
        {%endif%}

- id: home_workstation_update_mqtt_client_status
  alias: home_workstation_update_mqtt_client_status
  trigger:
    platform: state
    entity_id: sensor.home_workstation_nmap_tracker
    to: "Offline"
    for:
      minutes: 5
  action:
    - service: mqtt.publish
      data:
        topic: "smarthome/mqtt_client/status_update"
        payload: "Offline"
    - delay: '00:01:00'
    - service: script.turn_on
      entity_id: script.get_workstation_mqtt_client_status

- id: update_tracker_devices
  alias: update_tracker_devices
  trigger:
    - platform: time
      minutes: '/20'
      seconds: 00
  action:
    service: script.turn_on
    entity_id: script.update_all_devices

###########################################
###### Notifications Automations ##########
###########################################
- id: shabbat_candle_lighting_time_reminder
  alias: shabbat_candle_lighting_time_reminder
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    - condition: time
      weekday: fri
    - condition: template
      value_template: "{% if states.input_boolean.send_shabbat_notification_tomer.state == 'on' or states.input_boolean.send_shabbat_notification_hava.state == 'on' %}true{%else%}false{%endif%}"
    - condition: template
      value_template: "{{ as_timestamp(states.sensor.select_city_shabbat_start_time.state) | timestamp_custom('%y-%m-%d') == now().strftime('%y-%m-%d') }}"
    - condition: template
      value_template: >
        {% set shabbat_time = states.sensor.select_city_shabbat_start_time.state.split(" ")[1] %}
        {% set cur_time = now().strftime('%H:%M') %}
        {{ (shabbat_time.split(':')[0] | int * 60 + shabbat_time.split(':')[1] | int) - (cur_time.split(':')[0] | int * 60 + cur_time.split(':')[1] | int ) == states.sensor.shabbat_notify_minutes_start.state | int }}
  action:
    - service_template: >
        {% if states.input_boolean.send_shabbat_notification_tomer.state == 'on' and states.input_boolean.send_shabbat_notification_hava.state == 'on' %}notify.everyone
        {% elif states.input_boolean.send_shabbat_notification_hava.state == 'on' %}notify.telegram_hava_service
        {% elif states.input_boolean.send_shabbat_notification_tomer.state == 'on' %}notify.telegram_tomer_service
        {% endif %}
      data_template:
        title: "Shabbat Times"
        message: >
          Shabbat in {{ states.input_select.select_shabbat_city.state }} starts at {{ (as_timestamp(states.sensor.select_city_shabbat_start_time.state) | timestamp_custom('%H:%M')) }}.
          
          You have {{ states.sensor.shabbat_notify_minutes_start.state }} minutes left for candle lighting.
