##########################################
############## Home Assistant ############
##########################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Asia/Jerusalem
  customize: !include customize_ent.yaml
  packages: !include_dir_named packages

##########################################
############### Web Stuff ################
##########################################
http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy

##########################################
################ Includes ################
##########################################
switch: !include switches.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
device_tracker: !include device_tracker.yaml
notify: !include notifications.yaml
alexa: !include alexa.yaml
google_assistant: !include google_assistant.yaml

##########################################
######### Components Configuration #######
##########################################
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-script-custom-text.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-script-custom-text-es5.html
    - /local/custom_ui/state-card-tiles_es5.html

config:

updater:
  reporting: false

python_script:

mqtt:
  broker: !secret mosquitto_broker_ip
  port: !secret mosquitto_broker_port
  client_id: !secret mosquitto_ha_client_id
  username: !secret mosquitto_ha_user
  password: !secret mosquitto_ha_password
  discovery: false

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_tomer_chat_id
      - !secret telegram_hava_chat_id

lifx:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

hue:
  bridges:
    - host: !secret living_room_hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true
