##########################################
############## Home Assistant ############
##########################################
homeassistant:
  name: The Figenblat Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Asia/Jerusalem
  customize: !include customize_ent.yaml
  customize_domain:
    automation:
      initial_state: true
      hidden: true
    date_notifier:
      hidden: true
    scene:
      hidden: true
    sensor:
      force_update: true
  customize_glob:
    "sensor.*_door_sensor":
      icon: mdi:glassdoor
    "sensor.google_wifi_*_status":
      icon: mdi:wifi
    "sensor.*_traccar_geocode":
      hidden: true
    "sensor.shabbat_times_*":
      hidden: true
    "switch.*_light*":
      icon: mdi:lightbulb
    "switch.*_light_fixed":
      hidden: true
    "switch.*_ac_toggle":
      icon: mdi:power

##########################################
########## Basic Configuration ###########
##########################################
config:

history:

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

logbook:

logger:
  default: warning

lovelace:
  mode: yaml

system_health:

##########################################
######### Components Configuration #######
##########################################
alexa: !include alexa.yaml

amcrest:
  - host: !secret nursery_amcrest_cam_ip
    username: !secret nursery_cam_username
    password: !secret nursery_cam_password
    name: "Camera"
    port: !secret nursery_cam_port
    resolution: 'high'
    stream_source: 'rtsp'
    scan_interval: 3
    binary_sensors:
      - motion_detected
    sensors:
      - ptz_preset

automation: !include automations.yaml

cast:
  living_room_ghome_mini:
    - host: !secret living_room_ghome_mini_ip
  living_room_shield:
    - host: !secret living_room_shield_ip
  office_chromecast:
    - host: !secret office_chromecast_ip

climate: !include climates.yaml

cover:
  - platform: template
    covers:
      shabbat_notify_minutes_start:
        friendly_name: "Adjust Minutes"
        icon_template: mdi:alarm-plus
        # yamllint disable-line rule:line-length
        position_template: "{% if states.sensor.shabbat_notify_minutes_start.state ==  none %}30{% else %}{{ states.sensor.shabbat_notify_minutes_start.state | int}}{% endif %}"
        open_cover:
          service: input_text.set_value
          data_template:
            entity_id: input_text.shabbat_notify_minutes_start
            # yamllint disable-line rule:line-length
            value: "{{ [((states.input_text.shabbat_notify_minutes_start.state | int // 5 * 5) + 5), 90] | min }}"
        close_cover:
          service: input_text.set_value
          data_template:
            entity_id: input_text.shabbat_notify_minutes_start
            # yamllint disable-line rule:line-length
            value: "{{ [((states.input_text.shabbat_notify_minutes_start.state | int // 5 * 5) - 5), 0] | max }}"

date_notifier: !include date_notifiers.yaml

device_tracker: !include device_trackers.yaml

fan: !include fans.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg


google_assistant: !include google_assistant.yaml

hue:
  bridges:
    - host: !secret living_room_hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

input_boolean:
  send_shabbat_notification_tomer:
    name: "Notify Tomer"
    icon: mdi:send
  send_shabbat_notification_hava:
    name: "Notify Hava"
    icon: mdi:send

input_number: !include input_numbers.yaml

input_select: !include input_selects.yaml

input_text:
  shabbat_notify_minutes_start:
    name: shabbat_notify_minutes_start

lifx:

media_player:
  - platform: spotify
    client_id: !secret tomer_spotify_client_id
    client_secret: !secret tomer_spotify_client_secret
    name: "Tomer's Spotify"
    cache_path: ".spotify-token-cache"

mqtt:
  broker: !secret mosquitto_broker_ip
  port: !secret mosquitto_broker_port
  client_id: !secret mosquitto_ha_client_id
  username: !secret mosquitto_ha_user
  password: !secret mosquitto_ha_password
  discovery: false

notify:
  - platform: telegram
    name: telegram_tomer_service
    chat_id: !secret telegram_tomer_chat_id
  - platform: telegram
    name: telegram_hava_service
    chat_id: !secret telegram_hava_chat_id
  - platform: group
    name: everyone
    services:
      - service: telegram_tomer_service
      - service: telegram_hava_service

recorder:
  db_url: !secret hass_db_url
  purge_interval: 2
  purge_keep_days: 7
  include:
    domains:
      - climate
      - fan
      - input_boolean
      - input_number
      - input_select
      - input_text
      - sensor
      - light
  exclude:
    entities:
      - sensor.google_wifi_bedroom_uptime
      - sensor.google_wifi_guest_room_uptime
      - sensor.google_wifi_living_room_uptime
      - sensor.home_workstation_uptime_human
      - sensor.home_workstation_uptime_ticks
      - sensor.qnap_homenas_uptime

remote:
  - platform: harmony
    name: "Living Room Harmony Hub"
    host: !secret living_room_logitech_harmony_hub_ip
    activity: Watch TV

scene:
  - platform: lifx_cloud
    token: !secret lifx_cloud_token

script: !include scripts.yaml

sensor: !include sensors.yaml

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  manual: true

switch: !include switches.yaml

switcher_kis:
  phone_id: !secret switcher_phone_id
  device_id: !secret switcher_device_id
  device_password: !secret switcher_device_password

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_tomer_chat_id
      - !secret telegram_hava_chat_id

zone:
  - name: home
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    radius: 100
    icon: mdi:home

  - name: the_white_house
    latitude: !secret the_white_house_latitude
    longitude: !secret the_white_house_longitude
    radius: 100
    icon: mdi:home-heart

  - name: bynet
    latitude: !secret bynet_latitude
    longitude: !secret bynet_longitude
    radius: 200
    icon: mdi:worker
