- platform: template
  covers:
    lr_ac_temp_cover:
      position_template: "{% if states.sensor.lr_ac_temp_sensor ==  none %}25{% else %}{{ states.sensor.lr_ac_temp_sensor.state | int }}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.lr_ac_temp_text
          value: "{{ [((states.input_text.lr_ac_temp_text.state | int) + 1), 32] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.lr_ac_temp_text
          value: "{{ [((states.input_text.lr_ac_temp_text.state | int) - 1), 16] | max }}"
    shabbat_notify_minutes_start:
      position_template: "{% if states.sensor.shabbat_notify_minutes_start.state ==  none %}30{% else %}{{ states.sensor.shabbat_notify_minutes_start.state | int}}{% endif %}"
      open_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.shabbat_notify_minutes_start
          value: "{{ [((states.input_text.shabbat_notify_minutes_start.state | int // 5 * 5) + 5), 90] | min }}"
      close_cover:
        service: input_text.set_value
        data_template:
          entity_id: input_text.shabbat_notify_minutes_start
          value: "{{ [((states.input_text.shabbat_notify_minutes_start.state | int // 5 * 5) - 5), 0] | max }}"
