- platform: spotify
  client_id: !secret tomer_spotify_client_id
  client_secret: !secret tomer_spotify_client_secret
  
- platform: broadlink
  name: office_tv
  host: !secret office_broadlink_rm_mini_ip
  mac: !secret office_broadlink_rm_mini_mac
  ircodes_ini: 'ir_codes/office_tv.ini'
