- platform: spotify
  client_id: !secret tomer_spotify_client_id
  client_secret: !secret tomer_spotify_client_secret
  
- platform: samsungtv
  host: !secret living_room_samaung_tv_ip
  mac: !secret living_room_samaung_tv_mac

- platform: broadlink
  name: bedroom_tv
  host: !secret bedroom_broadlink_rm_mini_ip
  mac: !secret bedroom_broadlink_rm_mini_mac
  ircodes_ini: 'ir_codes/bedroom_tv.ini'
  
- platform: broadlink
  name: office_tv
  host: !secret office_broadlink_rm_mini_ip
  mac: !secret office_broadlink_rm_mini_mac
  ircodes_ini: 'ir_codes/office_tv.ini'
