- platform: group
  name: everyone
  services:
    - service: telegram_tomer_service
    - service: telegram_hava_service
    
- platform: telegram
  name: telegram_tomer_service
  chat_id: !secret telegram_tomer_chat_id
  
- platform: telegram
  name: telegram_hava_service
  chat_id: !secret telegram_hava_chat_id