- platform: template
  sensors:
    tomers_laptop_nmap_tracker:
      value_template: "{%if states.device_tracker.tomers_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
    havas_laptop_nmap_tracker:
      value_template: "{%if states.device_tracker.havas_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
    dash_wand_nmap_tracker:
      value_template: "{%if states.device_tracker.dash_wand.state == 'home'%}Online{%else%}Offline{%endif%}"
