- platform: broadlink
  host: !secret living_room_broadlink_rm_pro_ip
  mac: !secret living_room_broadlink_rm_pro_mac
  timeout: 15
  name: "living_room"
  monitored_conditions:
      - temperature

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
  monitored_conditions:
    - summary
    - hourly_summary
    - daily_summary
    - temperature
    - apparent_temperature
    - temperature_low
    - temperature_high
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - wind_speed
    - wind_bearing
    - pressure
    - icon

- platform: google_wifi
  host: !secret living_room_google_wifi_ip
  name: google_wifi_living_room
  monitored_conditions:
    - current_version
    - last_restart
    - new_version
    - status
    - uptime
  
- platform: google_wifi
  host: !secret guest_room_google_wifi_ip
  name: google_wifi_guest_room
  monitored_conditions:
    - current_version
    - last_restart
    - new_version
    - status
    - uptime
  
- platform: template
  sensors:
    lr_ac_temp_sensor:
      value_template: "{{ states.input_text.lr_ac_temp_text.state }}"
    hava_tracker_sensor:
      value_template: "{%if states.sensor.havas_phone_nmap_tracker.state == 'Online' %}Home{%else%}{{ states.input_text.hava_last_state.state }}{%endif%}"
    tomer_tracker_sensor:
      value_template: "{%if states.sensor.tomers_phone_nmap_tracker.state == 'Online' %}Home{%else%}{{ states.input_text.tomer_last_state.state }}{%endif%}"
    hava_owntracks_battery_sensor:
      value_template: "{%if states.device_tracker.havaphone_hpowntracks.attributes.battery is defined %}{{ states.device_tracker.havaphone_hpowntracks.attributes.battery | round }}{% else %}0{% endif %}"
      unit_of_measurement: '%'
      icon_template: >
        {%if states.device_tracker.havaphone_hpowntracks.attributes.battery is defined %}
          {% if ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 90) %} mdi:battery
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 80) %} mdi:battery-90
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 70) %} mdi:battery-80
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 60) %} mdi:battery-70
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 50) %} mdi:battery-60
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 40) %} mdi:battery-50
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 30) %} mdi:battery-40
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 20) %} mdi:battery-30
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 10) %} mdi:battery-20
          {% elif ((states.device_tracker.havaphone_hpowntracks.attributes.battery | round) > 0) %} mdi:battery-10
          {% endif%}
        {% else %} mdi:battery-unknown
        {% endif %}
    tomer_owntracks_battery_sensor:
      value_template: "{%if states.device_tracker.tomerphone_tpowntracks.attributes.battery is defined %}{{ states.device_tracker.tomerphone_tpowntracks.attributes.battery | round }}{% else %}0{% endif %}"
      unit_of_measurement: '%'
      icon_template: >
        {%if states.device_tracker.tomerphone_tpowntracks.attributes.battery is defined %}
          {% if ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 90) %} mdi:battery
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 80) %} mdi:battery-90
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 70) %} mdi:battery-80
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 60) %} mdi:battery-70
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 50) %} mdi:battery-60
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 40) %} mdi:battery-50
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 30) %} mdi:battery-40
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 20) %} mdi:battery-30
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 10) %} mdi:battery-20
          {% elif ((states.device_tracker.tomerphone_tpowntracks.attributes.battery | round) > 0) %} mdi:battery-10
          {% endif%}
        {% else %} mdi:battery-unknown
        {% endif %}
    home_workstation_nmap_tracker:
      value_template: "{%if states.device_tracker.home_workstation.state == 'home'%}Online{%else%}Offline{%endif%}"
    guest_room_yes_nmap_tracker:
      value_template: "{%if states.device_tracker.guest_room_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
    kitchen_echo_one_nmap_tracker:
      value_template: "{%if states.device_tracker.kitchen_echo_one.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_dot_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_dot.state == 'home'%}Online{%else%}Offline{%endif%}"
    switcher_v2_nmap_tracker:
      value_template: "{%if states.device_tracker.switcher_v2.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_yes_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
    hallway_netgear_hub5_nmap_tracker:
      value_template: "{%if states.device_tracker.hallway_netgear_hub5.state == 'home'%}Online{%else%}Offline{%endif%}"
    office_netgear_hub5_nmap_tracker:
      value_template: "{%if states.device_tracker.office_netgear_hub5.state == 'home'%}Online{%else%}Offline{%endif%}"
    shield_console_nmap_tracker:
      value_template: "{%if states.device_tracker.shield_console.state == 'home'%}Online{%else%}Offline{%endif%}"
    office_chromecast_nmap_tracker:
      value_template: "{%if states.device_tracker.office_chromecast.state == 'home'%}Online{%else%}Offline{%endif%}"
    xbox_360_nmap_tracker:
      value_template: "{%if states.device_tracker.xbox_360.state == 'home'%}Online{%else%}Offline{%endif%}"
    hue_bridge_nmap_tracker:
      value_template: "{%if states.device_tracker.hue_bridgehomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
    kitchen_fire_8_tablet_nmap_tracker:
      value_template: "{%if states.device_tracker.kitchen_fire_8_tablet.state == 'home'%}Online{%else%}Offline{%endif%}"
    office_dot_nmap_tracker:
      value_template: "{%if states.device_tracker.office_dot.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_ghome_mini_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_ghome_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
    kitchen_bar_sp2_nmap_tracker:
      value_template: "{%if states.device_tracker.kitchen_bar_sp2.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_rm_pro_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_rm_pro.state == 'home'%}Online{%else%}Offline{%endif%}"
    service_room_s1c_nmap_tracker:
      value_template: "{%if states.device_tracker.service_room_s1c.state == 'home'%}Online{%else%}Offline{%endif%}"
    tv_lifxz_led_nmap_tracker:
      value_template: "{%if states.device_tracker.tv_lifxz_led.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_harmony_hub_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_harmony_hub.state == 'home'%}Online{%else%}Offline{%endif%}"
    living_room_samsung_tv_nmap_tracker:
      value_template: "{%if states.device_tracker.living_room_samsung_tv.state == 'home'%}Online{%else%}Offline{%endif%}"
    tomers_phone_nmap_tracker:
      value_template: "{%if states.device_tracker.tomers_phone.state == 'home'%}Online{%else%}Offline{%endif%}"
    havas_phone_nmap_tracker:
      value_template: "{%if states.device_tracker.havas_phone.state == 'home'%}Online{%else%}Offline{%endif%}"
    tomers_laptop_nmap_tracker:
      value_template: "{%if states.device_tracker.tomers_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
    havas_laptop_nmap_tracker:
      value_template: "{%if states.device_tracker.havas_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
    dash_wand_nmap_tracker:
      value_template: "{%if states.device_tracker.dash_wand.state == 'home'%}Online{%else%}Offline{%endif%}"
    office_rm_mini_nmap_tracker:
      value_template: "{%if states.device_tracker.office_rm_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
    hallway_rf_gw_nmap_tracker:
      value_template: "{%if states.device_tracker.rfgw_hallwayhomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
    office_msensor_nmap_tracker:
      value_template: "{%if states.device_tracker.office_sensorhomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
    run_speed_test_last_run:
      value_template: "{{ as_timestamp(states.script.run_speed_test.attributes.last_triggered) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}"
    select_city_shabbat_start_time:
      value_template: >
        {% if states.input_select.select_shabbat_city.state == "Haifa" %}{{ states.sensor.shabbat_times_il_haifa.attributes.shabbat_start }}
        {% elif states.input_select.select_shabbat_city.state == "Rishon LeZion" %}{{ states.sensor.shabbat_times_il_rishon_lezion.attributes.shabbat_start }}
        {%endif%}
    select_city_shabbat_end_time:
      value_template: >
        {% if states.input_select.select_shabbat_city.state == "Haifa" %}{{ states.sensor.shabbat_times_il_haifa.attributes.shabbat_end }}
        {% elif states.input_select.select_shabbat_city.state == "Rishon LeZion" %}{{ states.sensor.shabbat_times_il_rishon_lezion.attributes.shabbat_end }}
        {%endif%}
    shabbat_notify_minutes_start:
      value_template: "{{ states.input_text.shabbat_notify_minutes_start.state }}"
    shabbat_start_notification_status:
      value_template: "{% if states.input_boolean.send_shabbat_notification_tomer.state == 'on' or states.input_boolean.send_shabbat_notification_hava.state == 'on' %}{{ states.sensor.shabbat_notify_minutes_start.state }} Minutes Before Start{%else%}Off{%endif%}"
    qnap_homenas_uptime:
      value_template: "{{ states.sensor.homenas_status.attributes.Uptime }}"
    home_workstation_uptime_human:
      value_template: >
        {% set full = states.sensor.home_workstation_uptime_ticks.state | int / 100 %}
        {% set days = (full / 86400) | int %}
        {% set hours = ((full % 86400) / 3600) | int %}
        {% set minutes = ((full % 3600) / 60) | int %}
        {% set seconds = (full % 60) | int %}
        {{ days }}D {{ hours }}H {{ minutes }}M {{ seconds }}S
    
- platform: mqtt
  state_topic: "smarthome/mqtt_client/status_update"
  name: "Workstation MQTT Status"
  
- platform: cert_expiry
  name: ha_duckdns_cert_expiry
  host: !secret duckdns_dns
  scan_interval: 86400

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  manual: true
  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use
      arg: /home
    - type: disk_free
      arg: /home
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: "cpu_temp"
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round }}'
  
- platform: qnap
  host: !secret qnap_ip
  port: !secret qnap_port
  username: !secret qnap_user
  password: !secret qnap_password
  ssl: false
  verify_ssl: false
  timeout: 30
  drives:
    - 0:1
  volumes:
    - DataVol1
  nics:
    - eth0
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_free
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used
    
- platform: google_geocode
  name: tomer_owntracks_gecode
  origin: device_tracker.tomerphone_tpowntracks
  options: street, city
  display_zone: hide
  api_key: !secret google_geocoding_api_key
  
- platform: google_geocode
  name: hava_owntracks_gecode
  origin: device_tracker.havaphone_hpowntracks
  options: street, city
  display_zone: hide
  api_key: !secret google_geocoding_api_key

- platform: shabbat_times
  geonames: "IL-Haifa,IL-Rishon LeZion"
  
- platform: snmp
  name: "home_workstation_uptime_ticks"
  host: !secret home_workstation_ip
  community: !secret home_workstation_snmp_community
  baseoid: 1.3.6.1.2.1.25.1.1.0
  accept_errors: true
  default_value: 0
  
- platform: xbox_live
  api_key: !secret xbox_api
  xuid: !secret xbox_xuid
  scan_interval: 60
  
- platform: broadlink_s1c
  ip_address: !secret hallways_broadlink_s1c_ip
  mac: !secret hallways_broadlink_s1c_mac

- platform: sql
  db_url: !secret hass_db_url
  queries:
    - name: db_size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema'
      column: 'value'
      unit_of_measurement: MB
    - name: db_days_kept
      query: 'SELECT DATEDIFF(CURRENT_DATE(), MIN(created)) AS "days_in_db" FROM homeassistant.events WHERE event_type != "state_changed"'
      column: 'days_in_db'
      unit_of_measurement: Days
    - name: last_recorder_status
      query: 'SELECT REPLACE(REPLACE(closed_incorrect, 0, "ok"), 1, "incorrect") AS "status" FROM homeassistant.recorder_runs WHERE run_id = (SELECT MAX(run_id) FROM homeassistant.recorder_runs WHERE end IS NOT NULL)'
      column: 'status'
  
- platform: qbittorrent
  url: !secret qbittorrent_webui_url
  name: "qbittorrent_client"
  username: !secret qbittorrent_webui_username
  password: !secret qbittorrent_webui_password

########################################
##### BRUH DIY MultiSensor Sensors #####
########################################
- platform: mqtt  
  state_topic: "multisensor/officenode"  
  name: "Office Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "multisensor/officenode"  
  name: "Office PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "multisensor/officenode"  
  name: "Office Temperature"  
  unit_of_measurement: "°C"  
  value_template: '{{ value_json.temperature | round(1) }}'  
