- platform: template
  switches:
    small_bathroom_light:
      friendly_name: "small_bathroom_light"
      value_template: "{{ states.switch.small_bathroom_light_fixed.state }}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.small_bathroom_light_fixed
        - delay:
            seconds: 1
        - service: switch.turn_on
          data:
            entity_id: switch.small_bathroom_light_fixed
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.small_bathroom_light_fixed
        - delay:
            seconds: 1
        - service: switch.turn_off
          data:
            entity_id: switch.small_bathroom_light_fixed
    main_hallway_light:
      friendly_name: "main_hallway_light"
      value_template: "{{ states.switch.main_hallway_light_fixed.state }}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.main_hallway_light_fixed
        - delay:
            seconds: 1
        - service: switch.turn_on
          data:
            entity_id: switch.main_hallway_light_fixed
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.main_hallway_light_fixed
        - delay:
            seconds: 1
        - service: switch.turn_off
          data:
            entity_id: switch.main_hallway_light_fixed
