homeassistant:
  customize:
    sensor.nursery_broadlink_a1_temperature:
      friendly_name: "Temperature"
    sensor.nursery_broadlink_a1_humidity:
      friendly_name: "Humidity"
      icon: mdi:water-percent
    sensor.nursery_broadlink_a1_air_quality:
      friendly_name: "Air Quality"
      icon: mdi:weather-windy
    sensor.nursery_broadlink_a1_light:
      friendly_name: "Light"
      icon: mdi:brightness-5
    sensor.nursery_broadlink_a1_noise:
      friendly_name: "Noise"
      icon: mdi:voice

sensor:
  - platform: broadlink
    name: nursery_broadlink_a1
    scan_interval: 30
    host: !secret nursery_broadlink_a1_ip
    mac: !secret nursery_broadlink_a1_mac
    monitored_conditions:
      - temperature
      - humidity
      - air_quality
      - light
      - noise
