homeassistant:
  customize:
    automation.shower_motion_sensor_motion_detected:
      friendly_name: "Shower Motion Detected: Light On"
      icon: mdi:lightbulb-on
      hidden: false
    automation.shower_motion_sensor_no_motion:
      friendly_name: "Shower No Motion 5 Min: Light Off"
      icon: mdi:lightbulb-outline
      hidden: false
    sensor.bedroom_humidity:
      friendly_name: "Bedroom Humidity"
    sensor.bedroom_pir:
      friendly_name: "Bedroom PIR"
    sensor.bedroom_temperature:
      friendly_name: "Bedroom Temperature" 
    sensor.broadlink_s1c_closet_room:
      friendly_name: "Closet Room Door"
    sensor.broadlink_s1c_shower_motion_sensor:
      friendly_name: "Shower Motion Sensor"
    sensor.bedroom_rm_mini_nmap_tracker:
      friendly_name: "Bedroom RM Mini"
      icon: mdi:remote
    sensor.bedroom_msensor_nmap_tracker:
      friendly_name: "Bedroom Multi-Sensor"
      icon: mdi:developer-board

automation:
  - id: shower_motion_sensor_motion_detected
    alias: shower_motion_sensor_motion_detected
    trigger:
      platform: state
      entity_id: sensor.broadlink_s1c_shower_motion_sensor
      to: 'motion_detected'
    action:
      service: switch.turn_on
      entity_id: switch.shower_light
  
  - id: shower_motion_sensor_no_motion
    alias: shower_motion_sensor_no_motion
    trigger:
      platform: state
      entity_id: sensor.broadlink_s1c_shower_motion_sensor
      to: 'no_motion'
      for: 
        minutes: 5
    action:
      service: switch.turn_off
      entity_id: switch.shower_light

sensor:
  - platform: mqtt  
    state_topic: "multisensor/bedroomnode"  
    name: bedroom_humidity
    unit_of_measurement: "%"  
    value_template: '{{ value_json.humidity | round(1) }}'  
  
  - platform: mqtt  
    state_topic: "multisensor/bedroomnode"  
    name: bedroom_pir
    value_template: '{{ value_json.motion }}'  
  
  - platform: mqtt  
    state_topic: "multisensor/bedroomnode"  
    name: bedroom_temperature
    unit_of_measurement: "°C"  
    value_template: '{{ value_json.temperature | round(1) }}' 
    
  - platform: template
    sensors:
      bedroom_rm_mini_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_rm_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
      bedroom_msensor_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_sensorhomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
  