homeassistant:
  customize:
    group.office_switches:
      friendly_name: "Lights"
    group.all_office_sensors:
      friendly_name: "Sensors"
      control: hidden
    group.office_view:
      friendly_name: "Office"
    group.qbittorent_client:
      friendly_name: "Qbittorrent"
      control: hidden
    group.multisensor_office:
      friendly_name: "MultiSensor Office"
      control: hidden

group:
  qbittorent_client:
    name: qbittorent_client
    entities:
      - sensor.qbittorrent_client_status
      - sensor.qbittorrent_client_down_speed
      - sensor.qbittorrent_client_up_speed

  office_view:
    name: office_view
    view: true
    entities:
      - group.multisensor_office
      - group.office_switches
      - group.office_ceiling_fan

  multisensor_office:  
    name: multisensor_office
    entities:  
      - sensor.office_temperature
      - sensor.office_humidity  
      - sensor.office_pir 
      
  office_switches:
    name: office_switches
    entities:
      - switch.office_light
