homeassistant:
  customize:
    group.living_room_view:
      friendly_name: "Living Room"
    group.living_room_ac:
      friendly_name: "Living Room AC"
      control: hidden
    group.living_room_tv_led:
      friendly_name: "TV Back Led"
      control: hidden
    group.all_living_room_sensors:
      friendly_name: "Sensors"
      icon: mdi:surround-sound
      control: hidden
    group.living_room_switches:
      friendly_name: "Lights"

group:
  living_room_view:
    name: living_room_view
    view: true
    entities:
      - group.all_living_room_sensors
      - group.living_room_tv_led
      - group.living_room_switches
      - group.living_room_ac
      - media_player.living_room_ghome_mini
      - media_player.samsung_tv_remote
      - media_player.living_room_shield
      - remote.living_room_harmony_hub

  all_living_room_sensors:
    name: all_living_room_sensors
    entities:
      - sensor.google_wifi_living_room_status
      - sensor.living_room_temperature

  living_room_tv_led:
    name: living_room_tv_led
    entities:
      - light.tv_lights
      - input_number.tv_led_brightness
      - input_number.tv_led_temperature
      - input_select.tv_led_color
      - input_select.tv_led_theme
      
  living_room_switches:
    name: living_room_switches
    entities:
      - light.tv_lights
      - light.living_room_night_light
      - switch.living_room_main_light
      - switch.living_room_small_light
      - switch.balcony_light
      - switch.entrance_light
      
  living_room_ac:
    name: living_room_ac
    entities:
      - climate.living_room_ac
      - switch.living_room_ac_toggle
      - input_number.living_room_ac_temperature_select
      - cover.living_room_ac_target_temperature
      - input_select.living_room_ac_operation_mode
      - input_select.living_room_ac_fan_level
