Minimal:
  dark-primary-color: "#192231"
  primary-color: "#98878f"
  light-primary-color: "#98878f"
  paper-toggle-button-checked-ink-color: "#494e6b"
  paper-toggle-button-checked-button-color: "#494e6b"
  paper-toggle-button-checked-bar-color: "#494e6b"
  paper-slider-knob-color: "#494e6b"
  paper-slider-knob-start-color: "#494e6b"
  paper-slider-pin-color: "#494e6b"
  paper-slider-active-color: "#494e6b"