Done:
  dark-primary-color: "#565656"
  primary-color: "#C09F80"
  light-primary-color: "#D7CEC7"
  paper-toggle-button-checked-ink-color: "#76323F"
  paper-toggle-button-checked-button-color: "#76323F"
  paper-toggle-button-checked-bar-color: "#76323F"
  paper-slider-knob-color: "#76323F"
  paper-slider-knob-start-color: "#76323F"
  paper-slider-pin-color: "#76323F"
  paper-slider-active-color: "#76323F"
  paper-slider-secondary-color: "#FFE0B2"