homeassistant:
  customize:
    switch.service_room_light:
      friendly_name: "Service Room Light"
      
switch:
  - platform: broadlink
    host: !secret service_room_light_broadlink_sc1_ip
    mac: !secret service_room_light_broadlink_sc1_mac
    friendly_name: "service_room_light"
    type: sp2

