homeassistant:
  customize:
    switch.kitchen_bar_light:
      friendly_name: "Bar light"
    switch.kitchen_main_light:
      friendly_name: "Kitchen Main Light"
      assumed_state: true
    switch.kitchen_main_light_fixed: # switch configuration is in living_room_switches.yaml
      hidden: true
    switch.kitchen_island_light:
      friendly_name: "Island Light"
      assumed_state: true
    switch.kitchen_island_light_fixed: # switch configuration is in living_room_switches.yaml
      hidden: true

switch:
  - platform: broadlink
    host: !secret kitchen_bar_light_broadlink_sp2_ip
    mac: !secret kitchen_bar_light_broadlink_sp2_mac
    friendly_name: "kitchen_bar_light"
    type: sp2
  
  - platform: template
    switches:
      kitchen_main_light:
        friendly_name: "kitchen_main_light"
        value_template: "{{ states.switch.kitchen_main_light_fixed.state }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_main_light_fixed
          - delay:
              seconds: 1
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_main_light_fixed
        turn_off:
          - service: switch.turn_off
            data:
              entity_id: switch.kitchen_main_light_fixed
          - delay:
              seconds: 1
          - service: switch.turn_off
            data:
              entity_id: switch.kitchen_main_light_fixed
      kitchen_island_light:
        friendly_name: "kitchen_island_light"
        value_template: "{{ states.switch.kitchen_island_light_fixed.state }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_island_light_fixed
          - delay:
              seconds: 1
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_island_light_fixed
        turn_off:
          - service: switch.turn_off
            data:
              entity_id: switch.kitchen_island_light_fixed
          - delay:
              seconds: 1
          - service: switch.turn_off
            data:
              entity_id: switch.kitchen_island_light_fixed

