homeassistant:
  customize:
    group.kitchen_view:
      friendly_name: "Kitchen"
    group.kitchen_switches:
      friendly_name: "Lights"
    group.all_kitchen_sensors:
      friendly_name: "Sensors"
      icon: mdi:surround-sound
      control: hidden

group:
  kitchen_view:
    name: kitchen_view
    view: true
    entities:
      - group.all_kitchen_sensors
      - group.kitchen_switches
    
  all_kitchen_sensors:
    name: all_kitchen_sensors
    entities:
      - sensor.broadlink_s1c_service_room

  kitchen_switches:
    name: kitchen_switches
    entities:
      - switch.kitchen_main_light
      - switch.kitchen_island_light
      - switch.kitchen_bar_light
      - switch.service_room_light

