LocateHavaIntent:
  action:
    service: script.turn_on
    data:
      entity_id: script.update_hava_devices
  speech:
    text: >
      {% if is_state('sensor.hava_tracker_sensor', 'not_home') %}
        I cannot find {{ HavaNick | lower | replace('my', 'your') }}, she is not at home.
      {% else %}
        {{ HavaNick | lower | replace('my', 'your') }}, is at {{states.sensor.hava_tracker_sensor.state | lower}}.
      {% endif %}
    
LocateTomerIntent:
  action:
    service: script.turn_on
    data:
      entity_id: script.update_tomer_devices
  speech:
    text: >
      {% if is_state('sensor.tomer_tracker_sensor', 'not_home') %}
        I cannnot find {{ TomerNick | lower | replace('my', 'your') }}, he is not at home.
      {% else %}
        {{ TomerNick | lower | replace('my', 'your') }}, is at {{states.sensor.tomer_tracker_sensor.state | lower}}.
      {% endif %}

FindTomerIphoneIntent:
  action:
    service: script.icloud_find_tomer_iphone
  speech:
    text: I've sent a Lost Phone Request to tomers icloud. Please wait for it to ring.

FindHavaIphoneIntent:
  action:
    service: script.icloud_find_hava_iphone
  speech:
    text: I've sent a Lost Phone Request to havas icloud. Please wait for it to ring.

GetSensorsStatesIntent:
  speech:
    text: >
      {% for sensor_name in states.group.all_s1c_sensors.attributes.entity_id %}{% set sensor_name = sensor_name.replace('sensor.', '') %}{%if loop.first %}Here are the sensors current states: the {% else %}the {% endif %}{{ states.sensor[sensor_name].attributes.friendly_name | lower }} is {{ states.sensor[sensor_name].state | lower }}{% if loop.last %}.{% else %},{% endif %}{% endfor %}

UpdateDevicesIntent:
  action:
    service: script.update_all_device
  speech:
    text: !include alexa_confirm.yaml
    
SendSensorsStatesIntent:
  action:
    service: script.get_sensors_report_notificiation_from_alexa
    data_template:
      send_to: '{{ SendTo }}'
  speech:
    text: I've request home to send a sensors report to {{ SendTo | lower | replace('my', 'your') }}

StartAction:
  action:
    service: mqtt.publish
    data_template:
      topic: "smarthome/mqtt_client/askmypc_action"
      payload: '{{ Action | lower }}'
      qos: 0
  speech:
    type: ssml
    text: "<speak>Sure thingboss.</speak>"
    