##########################################
######### On Event Automations ###########
##########################################
- id: on_start_event
  alias: on_start_event
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:01:00'
    - service: script.turn_on
      entity_id: script.correct_objects_values
    - service: script.turn_on
      entity_id: script.run_speed_test
    - service: script.turn_on
      entity_id: script.restart_s1c_addon_script
    - service: script.turn_on
      entity_id: script.get_den_mqtt_client_status
    #- delay: '00:01:00'
    #- service: script.turn_on
    #  entity_id: script.update_all_devices
    #- delay: '00:01:00'

##########################################
######### TV Led Automations #############
##########################################
- id: change_tv_led_brightness
  alias: change_tv_led_brightness
  trigger:
    platform: state
    entity_id: input_number.tv_led_brightness
  action:
    service: light.turn_on
    data_template:
      entity_id: light.tv_lights
      brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'

- id: change_tv_led_temperature
  alias: change_tv_led_temperature
  trigger:
    platform: state
    entity_id: input_number.tv_led_temperature
  action:
    service: light.turn_on
    data_template:
      entity_id: light.tv_lights
      color_temp: '{{ states.input_number.tv_led_temperature.state | int }}'
      brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'

- id: change_tv_led_color
  alias: change_tv_led_color
  trigger:
    platform: state
    entity_id: input_select.tv_led_color
  action:
    service: light.turn_on
    data_template:
      entity_id: light.tv_lights
      color_name: '{{ states.input_select.tv_led_color.state | string }}'
      brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'

- id: change_tv_led_theme
  alias: change_tv_led_theme
  trigger:
    platform: state
    entity_id: input_select.tv_led_theme
  action:
    service: script.tv_led_theme_select_script
    data_template:
      selected_theme: '{{ states.input_select.tv_led_theme.state }}'

##########################################
##### Living Room AC Automations #########
##########################################
- id: lr_ac_changes
  alias: lr_ac_changes
  trigger:
    - platform: state
      entity_id: sensor.lr_ac_temp_sensor
    - platform: state
      entity_id: input_select.lr_ac_state
    - platform: state
      entity_id: input_select.lr_ac_fan
  action:
    - condition: state
      entity_id: input_boolean.lr_ac_status
      state: 'on'
    - service: script.living_room_ac_check_state_script
      data_template:
        selecte_state: '{{ states.input_select.lr_ac_state.state }}'
        selected_fan: '{{ states.input_select.lr_ac_fan.state }}'
        selected_temp: '{{ states.sensor.lr_ac_temp_sensor.state }}'

- id: lr_ac_status_on
  alias: lr_ac_status_on
  trigger:
    platform: state
    entity_id: input_boolean.lr_ac_status
    to: 'on'
  action:
    service: script.living_room_ac_check_state_script
    data_template:
      selecte_state: '{{ states.input_select.lr_ac_state.state }}'
      selected_fan: '{{ states.input_select.lr_ac_fan.state }}'
      selected_temp: '{{ states.sensor.lr_ac_temp_sensor.state }}'
          
- id: lr_ac_status_off
  alias: lr_ac_status_off
  trigger:
    platform: state
    entity_id: input_boolean.lr_ac_status
    to: 'off'
  action:
    service: script.living_room_rm_pro_send_packet
    data:
      packet_code:
        - "JgDYAAABKpUTNxI4ExQTExQUFBQUNxI5EzgTOBM4ExQTFBMUFDcTOBUUEzgTNxMUFBMVOBI3FDgTOBQTFTgSExQUExQTFBMUFBMTFBQTExQUExM4FDgSFRMUExQTFBMUExQTFBMVExQUExMUFBMTFBQUEjgUFBQUFBQTFBMUFBQTFBQUExQTFRMUExQUFBMUFBQTFBMUFBQUExQUExQUFBMUExQUFBMUFBQTFBQUExQTFBQUExQTFBQ3FRQROBUUExQUExQUExUTFBM4EhQUNxM4FDgTOBM4FgANBQ=="

##########################################
######### Bedroom AC Automations #########
##########################################
- id: bedroom_ac_changes
  alias: bedroom_ac_changes
  trigger:
    - platform: state
      entity_id: sensor.bedroom_ac_temp_sensor
    - platform: state
      entity_id: input_select.bedroom_ac_state
    - platform: state
      entity_id: input_select.bedroom_ac_fan
  action:
    - condition: state
      entity_id: input_boolean.bedroom_ac_status
      state: 'on'
    - service: script.bedroom_ac_check_state_script
      data_template:
        selecte_state: '{{ states.input_select.bedroom_ac_state.state }}'
        selected_fan: '{{ states.input_select.bedroom_ac_fan.state }}'
        selected_temp: '{{ states.sensor.bedroom_ac_temp_sensor.state }}'

- id: bedroom_ac_status_on
  alias: bedroom_ac_status_on
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_ac_status
    to: 'on'
  action:
    service: script.bedroom_ac_check_state_script
    data_template:
      selecte_state: '{{ states.input_select.bedroom_ac_state.state }}'
      selected_fan: '{{ states.input_select.bedroom_ac_fan.state }}'
      selected_temp: '{{ states.sensor.bedroom_ac_temp_sensor.state }}'
          
- id: bedroom_ac_status_off
  alias: bedroom_ac_status_off
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_ac_status
    to: 'off'
  action:
    service: script.bedroom_rm_mini_send_packet
    data:
      packet_code:
        - "JgDKAJCMFzQSERM0EjQUEBMQEzQTEBMREjQVDxIREzQTMxMREjUSERI1EjQTNBM0ERISNRE2EDYRExATERIRExA2ERMQExE2EDcSNBQQEhESERMREhESEhATEBMRNhA3EDYRNhE2EKyPkhA2ERMQNhE2EBMRExA2ERMQExE2EBMRExA2ETYREhE2ERMQNhE2EDcQNhETEDYRNhE2EBMRExATERIRNhESERMQNxA2ETYREhETEBMREhETEBMSEhIREDcSNBE2ETYSNRIADQUAAAAAAAAAAAAAAAAAAA=="
        
- id: bedroom_ac_show_extra_controls_on
  alias: bedroom_ac_show_extra_controls_on
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_ac_status
    to: 'on'
  action:
    service: group.set_visibility
    data:
      entity_id: group.bedroom_ac_hidden_controls
      visible: true
      
- id: bedroom_ac_show_extra_controls_off
  alias: bedroom_ac_show_extra_controls_off
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_ac_status
    to: 'off'
  action:
    service: group.set_visibility
    data:
      entity_id: group.bedroom_ac_hidden_controls
      visible: false

###########################################
####### Door Sensors Automations ##########
###########################################
- id: small_bathroom_door_sensor_open
  alias: small_bathroom_door_sensor_open
  trigger:
    platform: state
    entity_id: sensor.small_bathroom_door_sensor
    from: 'Closed'
    to: 'Open'
  action:
    service: switch.turn_on
    entity_id: switch.small_bathroom_light
    
- id: main_bathroom_door_sensor_open
  alias: main_bathroom_door_sensor_open
  trigger:
    platform: state
    entity_id: sensor.main_bathroom_door_sensor
    from: 'Closed'
    to: 'Open'
  action:
    service: switch.turn_on
    entity_id: switch.main_bathroom_light
    
- id: closet_room_door_sensor_open
  alias: closet_room_door_sensor_open
  trigger:
    platform: state
    entity_id: sensor.closet_room_door_sensor
    from: 'Closed'
    to: 'Open'
  action:
    - service: switch.turn_on
      entity_id: switch.closet_room_light
    - service: switch.turn_on
      entity_id: switch.shower_light

- id: service_room_door_sensor_open
  alias: service_room_door_sensor_open
  trigger:
    platform: state
    entity_id: sensor.service_room_door_sensor
    from: 'Closed'
    to: 'Open'
  action:
    service: switch.turn_on
    entity_id: switch.service_room_light

- id: service_room_door_sensor_closed
  alias: service_room_door_sensor_closed
  trigger:
    platform: state
    entity_id: sensor.service_room_door_sensor
    from: 'Open'
    to: 'Closed'
  action:
    service: switch.turn_off
    entity_id: switch.service_room_light
    
###########################################
######### Tracking Automations ############
###########################################
- id: update_hava_last_state
  alias: update_hava_last_state
  trigger:
    - platform: state
      entity_id: device_tracker.havaphone_hpowntracks
    - platform: state
      entity_id: device_tracker.havaezra
  action:
    service: input_text.set_value
    data_template:
      entity_id: input_text.hava_last_state
      value: >
        {% if trigger.to_state.state == 'not_home' %}
          {%if trigger.entity_id == 'device_tracker.havaphone_hpowntracks' %}{{ states.sensor.hava_owntracks_gecode.state }}{%else%}{{ states.sensor.hava_icloud_gecode.state }}{%endif%}
        {%else%}{{ trigger.to_state.state | title }}
        {%endif%}

- id: update_tomer_last_state
  alias: update_tomer_last_state
  trigger:
    - platform: state
      entity_id: device_tracker.tomerphone_tpowntracks
    - platform: state
      entity_id: device_tracker.tomersiphone6s
  action:
    service: input_text.set_value
    data_template:
      entity_id: input_text.tomer_last_state
      value: >
        {% if trigger.to_state.state == 'not_home' %}
          {%if trigger.entity_id == 'device_tracker.tomerphone_tpowntracks' %}{{ states.sensor.tomer_owntracks_gecode.state }}{%else%}{{ states.sensor.tomer_icloud_gecode.state }}{%endif%}
        {%else%}{{ trigger.to_state.state | title }}
        {%endif%}

- id: den_pc_update_mqtt_client_status
  alias: den_pc_update_mqtt_client_status
  trigger:
    platform: state
    entity_id: sensor.den_pc_nmap_tracker
    to: "Offline"
    for:
      minutes: 5
  action:
    - service: mqtt.publish
      data:
        topic: "smarthome/mqtt_client/status_update"
        payload: "Offline"
    - delay: '00:01:00'
    - service: script.turn_on
      entity_id: script.get_den_mqtt_client_status
      
#- id: hava_tracking_group_change_state
#  alias: hava_tracking_group_change_state
#  trigger:
#    platform: state
#    entity_id: sensor.hava_tracker_sensor
#  action:
#    service: script.turn_on
#    entity_id: script.update_hava_devices

#- id: tomer_tracking_group_change_state
#  alias: tomer_tracking_group_change_state
#  trigger:
#    platform: state
#    entity_id: sensor.tomer_tracker_sensor
#  action:
#    service: script.turn_on
#    entity_id: script.update_tomer_devices

###########################################
###### Notifications Automations ##########
###########################################
- id: tomer_low_batt_notify
  alias: tomer_low_batt_notify
  trigger:
    platform: numeric_state
    entity_id: sensor.tomer_icloud_battery_sensor
    value_template: "{{ state.state }}"
    below: 31
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states.variable.tomer_low_batt_notification_sent.state | lower == 'false' }}"
      - condition: template
        value_template: "{{ states.device_tracker.tomersiphone6s.attributes.battery_status ==  'NotCharging' }}"
  action:
    - service: variable.set_variable
      data:
        variable: tomer_low_batt_notification_sent
        value: true
    - service: notify.ios_tomers_iphone6s
      data:
        message: "Battery level at or below 30%, please connect charger."
        title: "Battery Low Notification"
        
- id: tomer_low_batt_reset_variable
  alias: tomer_low_batt_reset_variable
  trigger:
    platform: numeric_state
    entity_id: sensor.tomer_icloud_battery_sensor
    value_template: "{{ state.state }}"
    above: 30
  condition:
    condition: template
    value_template: "{{ states.variable.tomer_low_batt_notification_sent.state.lower() == 'true' }}"
  action:
    service: variable.set_variable
    data:
      variable: tomer_low_batt_notification_sent
      value: false
        
- id: hava_low_batt_notify
  alias: hava_low_batt_notify
  trigger:
    platform: numeric_state
    entity_id: sensor.hava_icloud_battery_sensor
    value_template: "{{ state.state }}"
    below: 31
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states.variable.hava_low_batt_notification_sent.state | lower == 'false' }}"
      - condition: template
        value_template: "{{ states.device_tracker.havaezra.attributes.battery_status ==  'NotCharging' }}"
  action:
    - service: variable.set_variable
      data:
        variable: hava_low_batt_notification_sent
        value: true
    - service: notify.ios_hava_ezra
      data:
        message: "Battery level at or below 30%, please connect charger."
        title: "Battery Low Notification"

- id: hava_low_batt_reset_variable
  alias: hava_low_batt_reset_variable
  trigger:
    platform: numeric_state
    entity_id: sensor.hava_icloud_battery_sensor
    value_template: "{{ state.state }}"
    above: 30
  condition:
    condition: template
    value_template: "{{ states.variable.hava_low_batt_notification_sent.state.lower() == 'true' }}"
  action:
    service: variable.set_variable
    data:
      variable: hava_low_batt_notification_sent
      value: false
      
- id: shabbat_candle_lighting_time_reminder
  alias: shabbat_candle_lighting_time_reminder
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    - condition: time
      weekday: fri
    - condition: template
      value_template: "{% if states.input_boolean.send_shabbat_notification_tomer.state == 'on' or states.input_boolean.send_shabbat_notification_hava.state == 'on' %}true{%else%}false{%endif%}"
    - condition: template
      value_template: "{{ as_timestamp(states.sensor.select_city_shabbat_start_time.state) | timestamp_custom('%y-%m-%d') == now().strftime('%y-%m-%d') }}"
    - condition: template
      value_template: >
        {% set shabbat_time = states.sensor.select_city_shabbat_start_time.state.split(" ")[1] %}
        {% set cur_time = now().strftime('%H:%M') %}
        {{ (shabbat_time.split(':')[0] | int * 60 + shabbat_time.split(':')[1] | int) - (cur_time.split(':')[0] | int * 60 + cur_time.split(':')[1] | int ) == states.sensor.shabbat_notify_minutes_start.state | int }}
  action:
    - service_template: >
        {% if states.input_boolean.send_shabbat_notification_tomer.state == 'on' and states.input_boolean.send_shabbat_notification_hava.state == 'on' %}notify.all_ios
        {% elif states.input_boolean.send_shabbat_notification_hava.state == 'on' %}notify ios_hava_ezra
        {% elif states.input_boolean.send_shabbat_notification_tomer.state == 'on' %}notify.ios_tomers_iphone6s
        {% endif %}
      data_template:
        title: "Shabbat Times"
        message: >
          Shabbat in {{ states.input_select.select_shabbat_city.state }} starts at {{ (as_timestamp(states.sensor.select_city_shabbat_start_time.state) | timestamp_custom('%H:%M')) }}.
          
          You have {{ states.sensor.shabbat_notify_minutes_start.state }} minutes left for candle lighting.