##########################################
############## Home Assistant ############
##########################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Asia/Jerusalem
  customize: !include customize_ent.yaml
  customize_glob: !include customize_glob.yaml

##########################################
################## HTTP ##################
##########################################
http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate_path
  ssl_key: !secret http_ssl_key_path
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  cors_allowed_origins:
    - https://home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5

##########################################
######### Components Configuration #######
##########################################
frontend:
  themes: !include_dir_merge_named themes

config:

updater:
  reporting: false

#discovery:

#counter:

#conversation:

history:

logbook:

#sun:

ios:
#  push: !include ios_push.yaml

#tts:
#  - platform: google
  
light:
  - platform: lifx
  
hassio:

python_script:

mqtt:
  broker: !secret mosquitto_broker_ip
  port: !secret mosquitto_broker_port
  client_id: !secret mosquitto_broker_client_id
  username: !secret mosquitto_broker_user
  password: !secret mosquitto_broker_password
  discovery: false

logger:
  default: warning
#  logs:
#    custom_components.date_notifier: debug
#    homeassistant.components.notify: debug
#    homeassistant.components.python_script: debug
#    homeassistant.components.media_player: debug
#    homeassistant.components.emulated_hue: debug
#    homeassistant.components.alexa: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.climate: debug
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.sensor: debug

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_listen_port
  off_maps_to_on_domains:
    - scene
  expose_by_default: false
  exposed_domains:
    - switch
    - scene

alexa:

##########################################
################ Includes ################
##########################################
switch: !include switches.yaml
remote: !include remotes.yaml
media_player: !include media_players.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
variable: !include variables.yaml
input_text: !include input_text.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
intent_script: !include alexa_intents.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
date_notifier: !include date_notifiers.yaml