##########################################
############## Home Assistant ############
##########################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Asia/Jerusalem
  customize: !include customize_ent.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

##########################################
############### Web Stuff ################
##########################################
http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  
##########################################
######### Components Configuration #######
##########################################
frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-script-custom-text.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-script-custom-text-es5.html

config:

updater:
  reporting: false

#discovery:

#counter:

#conversation:

history:

logbook:

#sun:

ios:
#  push: !include ios_push.yaml

#tts:
#  - platform: google
  
hassio:

python_script:

mqtt:
  broker: !secret mosquitto_broker_ip
  port: !secret mosquitto_broker_port
  client_id: !secret mosquitto_broker_client_id
  username: !secret mosquitto_broker_user
  password: !secret mosquitto_broker_password
  discovery: false

#enable_loop_debug:
  
logger:
  default: error
#  logs:
#    homeassistant.components.recorder: debug
#    homeassistant.components.recorder.purge: debug
#    custom_components.smartthings_bridge: debug
#    custom_components.sensor.smartthings_bridge: debug
#    homeassistant.components.frontend: debug
#    custom_components.switcher_aio: debug
#    custom_components.sensor.broadlink_s1c: debug
#    custom_components.switcher: debug
#    homeassistant.components.alexa: debug
#    homeassistant.components.intent_script: debug
#    custom_components.date_notifier: debug
#    homeassistant.components.notify: debug
#    homeassistant.components.python_script: debug
#    homeassistant.components.media_player: debug
#    homeassistant.components.emulated_hue: debug
#    homeassistant.components.alexa: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.climate: debug
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.sensor: debug

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_listen_port
  off_maps_to_on_domains:
    - scene
  expose_by_default: false
  exposed_domains:
    - switch
    - scene
    - switcher_aio

alexa:

#israel_rails:
#  rosh_haayin_zafon_to_ta_university:
#    name: Home To School
#    from_station: '8800'
#    to_station: '3600'
#  ta_university_to_rosh_haayin_zafon:
#    name: School To Home
#    from_station: '3600'
#    to_station: '8800'

switcher_aio:
  phone_id: !secret switcher_phone_id
  device_id: !secret switcher_device_id
  device_password: !secret switcher_device_password
    
smartthings_bridge:
  url: !secret smartthings_bridge_url
  token: !secret smartthings_bridge_token
  
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_bot_api_key
#    allowed_chat_ids:
#      - !secret telegram_bot_chat_id

##########################################
################ Includes ################
##########################################
recorder: !include recorder.yaml
switch: !include switches.yaml
remote: !include remotes.yaml
media_player: !include media_players.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
variable: !include variables.yaml
input_text: !include input_text.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
intent_script: !include alexa_intents.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
date_notifier: !include date_notifiers.yaml
# shell_command: !include shell_commands.yaml
google_assistant: !include google_assistant.yaml
# history_graph: !include history_graph.yaml
light: !include lights.yaml