"sensor.google_wifi_*_status":
  icon: mdi:wifi
  
"switch.*_light":
  icon: mdi:lightbulb
  
"sensor.*_door_sensor":
  icon: mdi:glassdoor
  
"sensor.*":
  force_update: true
  
"automation.*":
  initial_state: true
