##########################################
########## One Time Reminders ############
##########################################
rafis_memorial_date:
  name: rafis_memorial_date
  hour: 10
  day: 21
  month: 2
  year: 2019
  message: "Dad's memorial"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"
  
tzilas_memorial_date:
  name: tzilas_memorial_date
  hour: 10
  day: 5
  month: 9
  year: 2018
  message: "Mom's memorial"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"

##########################################
########### Yearly Reminders #############
##########################################
wedding_day:
  name: wedding_day
  hour: 10
  day: 30
  month: 3
  message: "Wedding day"
  days_notice: 7
  notifier: "all_ios"
  countdown: true
  
havas_birthday:
  name: havas_birthday
  hour: 10
  day: 30
  month: 3
  message: "Hava's birthday"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"
  countdown: true
  
tomers_birthday:
  name: tomers_birthday
  hour: 10
  day: 2
  month: 2
  message: "Hava's birthday"
  days_notice: 4
  notifier: "ios_hava_ezra"
  countdown: true

matans_birthday:
  name: matans_birthday
  hour: 10
  day: 8
  month: 2
  message: "Matan's birthday"
  days_notice: 2
  notifier: "all_ios"
  countdown: true
  
gilis_birthday:
  name: gilis_birthday
  hour: 10
  day: 25
  month: 2
  message: "Gili's birthday"
  days_notice: 2
  notifier: "all_ios"
  countdown: true
  
mayas_birthday:
  name: mayas_birthday
  hour: 10
  day: 24
  month: 4
  message: "Maya's birthday"
  days_notice: 2
  notifier: "all_ios"
  countdown: true
  
twins_birthday:
  name: twins_birthday
  hour: 10
  day: 13
  month: 4
  message: "The twins's birthday"
  days_notice: 2
  notifier: "all_ios"
  countdown: true
  
tzilas_birthday:
  name: tzilas_birthday
  hour: 10
  day: 2
  month: 3
  message: "Mom's birthday"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"
  
rafis_birthday:
  name: rafis_birthday
  hour: 10
  day: 5
  month: 6
  message: "Dad's birthday"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"
  
tzilas_passing_date:
  name: tzilas_passing_date
  hour: 10
  day: 1
  month: 8
  message: "Mom's passing jewish date is the 25 of Elul 28/09/2016, please set a new reminder with the gregorian date for the memorial"
  days_notice: 0
  notifier: "ios_tomers_iphone6s"
  
rafis_passing_date:
  name: rafis_passing_date
  hour: 10
  day: 15
  month: 1
  message: "Dad's passing jewish date is the 16 of Adar 16/02/2014, please set a new reminder with the gregorian date for the memorial"
  days_notice: 0
  notifier: "ios_tomers_iphone6s"

hana_birthday_hava:
  name: hana_birthday
  hour: 10
  day: 25
  month: 10
  message: "Hana's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

dganit_birthday:
  name: dganit_birthday
  hour: 10
  day: 23
  month: 9
  message: "Dganit's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

yossi_birthday:
  name: yossi_birthday
  hour: 10
  day: 2
  month: 5
  message: "Yossi's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

sharon_birthday:
  name: sharon_birthday
  hour: 10
  day: 18
  month: 5
  message: "Sharon's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

menachem_birthday:
  name: menachem_birthday
  hour: 10
  day: 16
  month: 7
  message: "Menachem's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

daniel_birthday:
  name: daniel_birthday
  hour: 10
  day: 6
  month: 6
  message: "Daniels's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true
  
liel_birthday:
  name: liel_birthday
  hour: 10
  day: 23
  month: 1
  message: "Liel's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true
  
tuval_birthday:
  name: tuval_birthday
  hour: 10
  day: 11
  month: 8
  message: "Tuval's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true

aviv_birthday:
  name: aviv_birthday
  hour: 10
  day: 2
  month: 11
  message: "Aviv's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true
  
shalev_birthday:
  name: shalev_birthday
  hour: 10
  day: 15
  month: 5
  message: "Shalev's birthday"
  days_notice: 2
  notifier: all_ios
  countdown: true
  
##########################################
########## Monthly Reminders #############
##########################################
# Monthly Reminder will be send on the 19th of every month at 21:27
#monthly_reminder:
#  name: "montly test"
#  hour: 21
#  minute: 27
#  day: 19
#  message: "montly test2"
#  days_notice: 0
#  notifier: "ios_tomers_iphone6s"

##########################################
########### Daily Reminders ##############
########################################## 
# Daily Reminder will be send every day at 21:28
#daily_reminder:
#  name: "daily test"
#  hour: 21
#  minute: 28
#  message: "daily test"
#  notifier: "ios_tomers_iphone6s"