##########################################
########## One Time Reminders ############
##########################################
tomer_dental_ct:
  name: tomer_dental_ct
  hour: 10
  day: 1
  month: 3
  year: 2018
  message: "Dental CT in Dent-Or in rishon lezion, remmeber to take apropriate papers"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"
  
tomer_dental_hygienist:
  name: tomer_dental_hygienist
  hour: 16
  day: 13
  month: 3
  year: 2018
  message: "Dental hygienist appointment at 16:00 in rishon lezion clinic with ms Sabbag"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"

tomer_dental_ct_examination:
  name: tomer_dental_ct_examination
  hour: 9
  day: 14
  month: 3
  year: 2018
  message: "Dental CT examination appointment at 09:00 in rishon lezion clinic with dr Shoaht"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"

tomer_dental_tooth_implent:
  name: tomer_dental_tooth_implent
  hour: 11
  minute: 30
  day: 28
  month: 3
  year: 2018
  message: "Upper tooth implent appointment at 11:30 in rishon lezion clinic with dr Shoaht"
  days_notice: 2
  notifier: "ios_tomers_iphone6s"
  
rafis_memorial_date:
  name: rafis_memorial_date
  hour: 10
  day: 3
  month: 3
  year: 2018
  message: "Dad's memorial"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"
  
tzilas_memorial_date:
  name: tzilas_memorial_date
  hour: 10
  day: 5
  month: 9
  year: 2018
  message: "Mom's memorial"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"

##########################################
########### Yearly Reminders #############
##########################################
wedding_day:
  name: wedding_day
  hour: 10
  day: 30
  month: 3
  message: "Wedding day"
  days_notice: 7
  notifier: "all_ios"
  
havas_birthday:
  name: havas_birthday
  hour: 10
  day: 30
  month: 3
  message: "Hava's birthday"
  days_notice: 7
  notifier: "ios_tomers_iphone6s"
  
tomers_birthday:
  name: tomers_birthday
  hour: 10
  day: 2
  month: 2
  message: "Hava's birthday"
  days_notice: 4
  notifier: "ios_hava_ezra"

matans_birthday:
  name: matans_birthday
  hour: 10
  day: 8
  month: 2
  message: "Matan's birthday"
  days_notice: 1
  notifier: "all_ios"
  
gilis_birthday:
  name: gilis_birthday
  hour: 10
  day: 25
  month: 2
  message: "Gili's birthday"
  days_notice: 1
  notifier: "all_ios"
  
mayas_birthday:
  name: mayas_birthday
  hour: 10
  day: 24
  month: 4
  message: "Maya's birthday"
  days_notice: 1
  notifier: "all_ios"
  
twins_birthday:
  name: twins_birthday
  hour: 10
  day: 13
  month: 4
  message: "The twins's birthday"
  days_notice: 2
  notifier: "all_ios"
  
tzilas_birthday:
  name: tzilas_birthday
  hour: 10
  day: 2
  month: 3
  message: "Mom's birthday"
  days_notice: 1
  notifier: "ios_tomers_iphone6s"
  
rafis_birthday:
  name: rafis_birthday
  hour: 10
  day: 5
  month: 6
  message: "Dad's birthday"
  days_notice: 1
  notifier: "ios_tomers_iphone6s"
  
tzilas_passing_date:
  name: tzilas_passing_date
  hour: 10
  day: 1
  month: 8
  message: "Mom's passing jewish date is the 25 of Elul, please set a new reminder with the gregorian date for the memorial"
  days_notice: 0
  notifier: "ios_tomers_iphone6s"
  
rafis_passing_date:
  name: rafis_passing_date
  hour: 10
  day: 15
  month: 1
  message: "Dad's passing jewish date is the 16 of Adar, please set a new reminder with the gregorian date for the memorial"
  days_notice: 0
  notifier: "ios_tomers_iphone6s"

##########################################
########## Monthly Reminders #############
##########################################
# Monthly Reminder will be send on the 19th of every month at 21:27
#monthly_reminder:
#  name: "montly test"
#  hour: 21
#  minute: 27
#  day: 19
#  message: "montly test2"
#  days_notice: 0
#  notifier: "ios_tomers_iphone6s"

##########################################
########### Daily Reminders ##############
########################################## 
# Daily Reminder will be send every day at 21:28
#daily_reminder:
#  name: "daily test"
#  hour: 21
#  minute: 28
#  message: "daily test"
#  notifier: "ios_tomers_iphone6s"