lr_ac_status:
  name: "lr_ac_status"
  initial: off
bedroom_ac_status:
  name: "bedroom_ac_status"
  initial: off
send_shabbat_notification_tomer:
  name: "send_shabbat_notification_tomer"
send_shabbat_notification_hava:
  name: "send_shabbat_notification_hava"