tv_led_color:
  name: tv_led_color
  options:
    - Red
    - Blue
    - Green
    - Gold
    - Orange
    - Pink
    - Purple

tv_led_theme:
  name: tv_led_theme
  options:
    - Blissful
    - Cheerful
    - Dream
    - Energizing
    - Epic
    - Exciting
    - Focusing
    - Halloween
    - Hanukkah
    - Holy
    - Independence Day
    - Intense
    - Mellow
    - Peaceful
    - Powerful
    - Relaxing
    - Santa
    - Serene
    - Soothing
    - Sports
    - Tranquil
    - Warming
    
lr_ac_state:
  name: lr_ac_state
  options :
    - HEAT
    - COOL

lr_ac_fan:
  name: lr_ac_fan
  options:
    - LOW
    - MED
    - HIGH
    - AUTO
    
bedroom_ac_state:
  name: bedroom_ac_state
  options :
    - HEAT
    - COOL

bedroom_ac_fan:
  name: bedroom_ac_fan
  options:
    - LOW
    - MED
    - HIGH
    - AUTO

select_shabbat_city:
  name: select_shabbat_city
  options:
    - Rishon LeZion
    - Haifa
    
select_log_level:
  name: select_log_level
  options:
    - critical
    - fatal
    - error
    - warning
    - warn
    - info
    - debug
    - notset
  initial: error
  
office_ceiling_fan_level:
  name: office_ceiling_fan_level
  options:
    - OFF_
    - LOW
    - MED
    - HIGH