lr_ac_temp_text:
  name: lr_ac_temp_text
bedroom_ac_temp_text:
  name: bedroom_ac_temp_text
hava_last_state:
  name: hava_last_state
tomer_last_state:
  name: tomer_last_state
shabbat_notify_minutes_start:
  name: shabbat_notify_minutes_start