tv_led_brightness:
  name: tv_led_brightness
  initial: 75
  min: 0
  max: 100
  step: 5

tv_led_temperature:
  name: tv_led_temperature
  initial: 300
  min: 154
  max: 500
  step: 10
  
shabbat_notify_minutes_start:
  name: shabbat_notify_minutes_start
  initial: -180
  min: -200
  max: 120
  step: 1
  mode: box