db_url: !secret hass_db_url
purge_interval: 2
purge_keep_days: 7
include:
  domains:
    - input_boolean
    - input_number
    - input_select
    - input_text
    - sensor
    - variable
  entities:
    - switcher_aio.notification_service_input_select
    - switcher_aio.timer_minutes_input_select
#exclude:
#  domains:
#    - automation
#    - cover
#    - date_notifier
#    - device_tracker
#    - group
#    - light
#    - media_player
#    - remote
#    - scene
#    - script
#    - sensor
#    - switch
#    - zone
    