- platform: lifx_cloud
  token: !secret lifx_cloud_token
  
- name: leaving_home
  entities:
    script.leaving_home:
      state: on

- name: watch_tv
  entities:
    remote.living_room_harmony_hub:
      state: on
      activity: "Watch TV"
    script.watch_living_room_tv:
      state: on
    
- name: watch_movie
  entities:
    remote.living_room_harmony_hub:
      state: on
      activity: "Watch Shield"
    script.watch_living_room_tv:
      state: on

- name: sleep_time
  entities:
    script.sleep_time:
      state: on
      
- name: turn_on_boiler_15_min
  entities:
    script.turn_on_boiler_15_min:
      state: on
      
- name: turn_on_boiler_30_min
  entities:
    script.turn_on_boiler_30_min:
      state: on
      
- name: turn_on_boiler_45_min
  entities:
    script.turn_on_boiler_45_min:
      state: on
      
- name: turn_on_boiler_60_min
  entities:
    script.turn_on_boiler_60_min:
      state: on
      
- name: turn_on_boiler_1_h
  entities:
    script.turn_on_boiler_60_min:
      state: on