homeassistant:
  customize:
    sensor.living_room_temperature:
      friendly_name: "Living Room Temperature"
      icon: mdi:temperature-celsius
    

sensor:
  - platform: broadlink
    host: !secret living_room_broadlink_rm_pro_ip
    mac: !secret living_room_broadlink_rm_pro_mac
    timeout: 15
    name: "living_room"
    monitored_conditions:
        - temperature
