homeassistant:
  customize:
    media_player.samsung_tv_remote:
      friendly_name: "Living Room Samsung TV"
      icon: mdi:television
    media_player.living_room_shield:
      friendly_name: "Living Room Nvidie Shield"
    sensor.living_room_harmony_hub_nmap_tracker:
      friendly_name: "Living Room Harmony Hub"
      icon: mdi:remote
    sensor.living_room_samsung_tv_nmap_tracker:
      friendly_name: "Living Room Samsung TV"
      icon: mdi:television
    script.watch_living_room_tv:
      hidden: true
    scene.watch_tv:
      friendly_name: "Watch TV"
    scene.watch_movie:
      friendly_name: "Watch A Movie"
    remote.living_room_harmony_hub:
      friendly_name: "Living Room Harmony Hub"
    sensor.living_room_yes_nmap_tracker:
      friendly_name: "Living Room Yes"
      icon: mdi:television-classic
    sensor.shield_console_nmap_tracker:
      friendly_name: "Shield Console"
      icon: mdi:android

media_player:
  - platform: samsungtv
    host: !secret living_room_samaung_tv_ip
    mac: !secret living_room_samaung_tv_mac

cast:
  living_room_shield:
    - host: !secret living_room_shield_ip
    
remote:
  - platform: harmony
    name: living_room_harmony_hub
    host: !secret living_room_logitech_harmony_hub_ip
    activity: Watch TV
    
scene:
  - name: watch_tv
    entities:
      remote.living_room_harmony_hub:
        state: on
        activity: "Watch TV"
      script.watch_living_room_tv:
        state: on
      
  - name: watch_movie
    entities:
      remote.living_room_harmony_hub:
        state: on
        activity: "Watch Shield"
      script.watch_living_room_tv:
        state: on
        
script:
  watch_living_room_tv:
    sequence:
      - service: scene.turn_on
        entity_id: scene.energizing_lights
      - service: switch.turn_off
        entity_id: switch.kitchen_main_light
      - delay:
          milliseconds: 1500
      - service: switch.turn_off
        entity_id: switch.living_room_main_light
      - delay:
          milliseconds: 500
      - service: switch.turn_off
        entity_id: switch.living_room_small_light
      - delay:
          milliseconds: 500
      - service: switch.turn_off
        entity_id: switch.balcony_light
      - delay:
          milliseconds: 500
      - service: switch.turn_off
        entity_id: switch.main_hallway_light
      - delay:
          milliseconds: 1500
      - service: switch.turn_off
        entity_id: switch.entrance_light
      - delay:
          milliseconds: 500
      - service: switch.turn_off
        entity_id: switch.small_hallway_light
      - delay:
          milliseconds: 500
      - service: light.turn_off
        entity_id: light.living_room_night_light
      - service: switch.turn_off
        entity_id: switch.kitchen_bar_light
      - service: switch.turn_off
        entity_id: switch.service_room_light
      - service: switch.turn_off
        entity_id: switch.kitchen_island_light
      - service: switch.turn_off
        entity_id: switch.office_light
        
sensor:
  - platform: template
    sensors:
      living_room_harmony_hub_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_harmony_hub.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_samsung_tv_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_samsung_tv.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_yes_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
      shield_console_nmap_tracker:
        value_template: "{%if states.device_tracker.shield_console.state == 'home'%}Online{%else%}Offline{%endif%}"
