homeassistant:
  customize:
    light.tv_lights: # this light is configured within the lifx component
      friendly_name: "TV Back Led"
    light.living_room_night_light: # this light is configured within the hue component
      friendly_name: "Night Light"
      supported_features: 43
    light.nursery_ambiance_1: #this is actually the living night light, I preffer controlling it via its group light.living_room_night_light
      hidden: true
    script.tv_led_theme_select_script:
      hidden: true
    input_number.tv_led_brightness:
      friendly_name: "Brightness"
      icon: mdi:brightness-6
    input_number.tv_led_temperature:
      friendly_name: "Color Temperature"
      icon: mdi:oil-temperature
    input_select.tv_led_color:
      friendly_name: "Color"
      icon: mdi:format-color-fill
    input_select.tv_led_theme:
      friendly_name: "Theme"
      icon: mdi:white-balance-iridescent

automation:
  - id: change_tv_led_brightness
    alias: change_tv_led_brightness
    trigger:
      platform: state
      entity_id: input_number.tv_led_brightness
    action:
      service: light.turn_on
      data_template:
        entity_id: light.tv_lights
        brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'
  
  - id: change_tv_led_temperature
    alias: change_tv_led_temperature
    trigger:
      platform: state
      entity_id: input_number.tv_led_temperature
    action:
      service: light.turn_on
      data_template:
        entity_id: light.tv_lights
        color_temp: '{{ states.input_number.tv_led_temperature.state | int }}'
        brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'
  
  - id: change_tv_led_color
    alias: change_tv_led_color
    trigger:
      platform: state
      entity_id: input_select.tv_led_color
    action:
      service: light.turn_on
      data_template:
        entity_id: light.tv_lights
        color_name: '{{ states.input_select.tv_led_color.state | string }}'
        brightness_pct: '{{ states.input_number.tv_led_brightness.state | int }}'
  
  - id: change_tv_led_theme
    alias: change_tv_led_theme
    trigger:
      platform: state
      entity_id: input_select.tv_led_theme
    action:
      service: script.tv_led_theme_select_script
      data_template:
        selected_theme: '{{ states.input_select.tv_led_theme.state }}'
        
input_number:
  tv_led_brightness:
    name: tv_led_brightness
    initial: 75
    min: 0
    max: 100
    step: 5
  tv_led_temperature:
    name: tv_led_temperature
    initial: 300
    min: 154
    max: 500
    step: 10
  
input_select:
  tv_led_color:
    name: tv_led_color
    options:
      - Red
      - Blue
      - Green
      - Gold
      - Orange
      - Pink
      - Purple
  tv_led_theme:
    name: tv_led_theme
    options:
      - Blissful
      - Cheerful
      - Dream
      - Energizing
      - Epic
      - Exciting
      - Focusing
      - Halloween
      - Hanukkah
      - Holy
      - Independence Day
      - Intense
      - Mellow
      - Peaceful
      - Powerful
      - Relaxing
      - Santa
      - Serene
      - Soothing
      - Sports
      - Tranquil
      - Warming
      
scene:
  - platform: lifx_cloud
    token: !secret lifx_cloud_token
    
script:
  tv_led_theme_select_script:
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: >
            {% if (selected_theme == "Blissful") %} scene.blissful_lights
            {% elif (selected_theme == "Cheerful") %} scene.cheerful_lights
            {% elif (selected_theme == "Dream") %} scene.dream_lights
            {% elif (selected_theme == "Energizing") %} scene.energizing_lights
            {% elif (selected_theme == "Epic") %} scene.epic_lights
            {% elif (selected_theme == "Exciting") %} scene.exciting_lights
            {% elif (selected_theme == "Focusing") %} scene.focusing_lights
            {% elif (selected_theme == "Halloween") %} scene.halloween_lights
            {% elif (selected_theme == "Hanukkah") %} scene.hanukkah_lights
            {% elif (selected_theme == "Holy") %} scene.holy_lights
            {% elif (selected_theme == "Independence Day") %} scene.independence_day_lights
            {% elif (selected_theme == "Intense") %} scene.intense_lights
            {% elif (selected_theme == "Mellow") %} scene.mellow_lights
            {% elif (selected_theme == "Peaceful") %} scene.peaceful_lights
            {% elif (selected_theme == "Powerful") %} scene.powerful_lights
            {% elif (selected_theme == "Relaxing") %} scene.relaxing_lights
            {% elif (selected_theme == "Santa") %} scene.santa_lights
            {% elif (selected_theme == "Serene") %} scene.serene_lights
            {% elif (selected_theme == "Soothing") %} scene.soothing_lights
            {% elif (selected_theme == "Sports") %} scene.sports_lights
            {% elif (selected_theme == "Tranquil") %} scene.tranquil_lights
            {% elif (selected_theme == "Warming") %} scene.warming_lights
            {% endif %}
