homeassistant:
  customize:
    sensor.home_workstation_mqtt_client_status:
      friendly_name: "Workstation Mqtt Client"
      icon: mdi:developer-board
    sensor.tomerfu:
      friendly_name: "Xbox Live Account"
    sensor.home_workstation_uptime_human:
      friendly_name: "Workstation Uptime"
      icon: mdi:timelapse
    sensor.home_workstation_uptime_ticks:
      hidden: true
    sensor.qbittorrent_client_down_speed:
      friendly_name: "Down Speed"
      icon: mdi:download-network
    sensor.qbittorrent_client_status:
      friendly_name: "Status"
      icon: mdi:network
    sensor.qbittorrent_client_up_speed:
      friendly_name: "Up Speed"
      icon: mdi:upload-network
    sensor.office_humidity:
      friendly_name: "Office Humidity"
    sensor.office_pir:
      friendly_name: "Office PIR"
    sensor.office_temperature:
      friendly_name: "Office Temperature"

sensor:
  - platform: template
    sensors:
      home_workstation_uptime_human:
        value_template: >
          {% set full = states.sensor.home_workstation_uptime_ticks.state | int / 100 %}
          {% set days = (full / 86400) | int %}
          {% set hours = ((full % 86400) / 3600) | int %}
          {% set minutes = ((full % 3600) / 60) | int %}
          {% set seconds = (full % 60) | int %}
          {{ days }}D {{ hours }}H {{ minutes }}M {{ seconds }}S

  - platform: mqtt
    state_topic: "smarthome/mqtt_client/status_update"
    name: "Workstation MQTT Status"
    
  - platform: snmp
    name: "home_workstation_uptime_ticks"
    host: !secret home_workstation_ip
    community: !secret home_workstation_snmp_community
    baseoid: 1.3.6.1.2.1.25.1.1.0
    accept_errors: true
    default_value: 0
    
  - platform: xbox_live
    api_key: !secret xbox_api
    xuid: !secret xbox_xuid
    scan_interval: 60

  - platform: qbittorrent
    url: !secret qbittorrent_webui_url
    name: "qbittorrent_client"
    username: !secret qbittorrent_webui_username
    password: !secret qbittorrent_webui_password

  - platform: mqtt  
    state_topic: "multisensor/officenode"  
    name: office_humidity
    unit_of_measurement: "%"  
    value_template: '{{ value_json.humidity | round(1) }}'  
  
  - platform: mqtt  
    state_topic: "multisensor/officenode"  
    name: office_pir 
    value_template: '{{ value_json.motion }}'  
  
  - platform: mqtt  
    state_topic: "multisensor/officenode"  
    name: office_temperature  
    unit_of_measurement: "°C"  
    value_template: '{{ value_json.temperature | round(1) }}'  
