homeassistant:
  customize:
    group.office_switches:
      friendly_name: "Lights"
    group.all_office_sensors:
      friendly_name: "Sensors"
      control: hidden
    group.office_view:
      friendly_name: "Office"
      order: 9
    group.qbittorent_client:
      friendly_name: "Qbittorrent"
      control: hidden
    group.office_ceiling_fan:
      friendly_name: "Ceiling Fan"
      control: hidden

group:
  qbittorent_client:
    name: qbittorent_client
    entities:
      - sensor.qbittorrent_client_status
      - sensor.qbittorrent_client_down_speed
      - sensor.qbittorrent_client_up_speed

  office_view:
    name: office_view
    view: true
    entities:
      - group.all_office_sensors
      - group.office_switches
      - group.office_ceiling_fan

  all_office_sensors:  
    name: all_office_sensors
    entities:  
      - sensor.office_temperature
      - sensor.office_humidity  
      - sensor.office_pir 
      
  office_switches:
    name: office_switches
    entities:
      - switch.office_light
      
  office_ceiling_fan:
    name: office_ceiling_fan
    entities:
      - script.set_office_ceiling_fan_off
      - script.set_office_ceiling_fan_low
      - script.set_office_ceiling_fan_medium
      - script.set_office_ceiling_fan_high
      - fan.office_ceiling_fan


