homeassistant:
  customize:
    group.guest_room_view:
      friendly_name: "Guest Room"
      order: 8
    group.guest_room_switches:
      friendly_name: "Lights"
    group.all_guest_room_sensors:
      friendly_name: "Sensors"
      icon: mdi:surround-sound
      control: hidden
      
group:
  guest_room_view:
    name: guest_room_view
    view: true
    entities:
      - group.all_guest_room_sensors
      - group.guest_room_switches
  guest_room_switches:
    name: guest_room_switches
    entities:
      - switch.guest_room_light
  all_guest_room_sensors:
    name: all_guest_room_sensors
    entities:
      - sensor.google_wifi_guest_room_status



    

    
