homeassistant:
  customize:
    switch.shower_light:
      friendly_name: "Shower Light" # switch configuration is in living_room_switches.yaml
    switch.closet_room_light:
      friendly_name: "Closet Room Light" # switch configuration is in living_room_switches.yaml
    switch.bedroom_main_light:
      friendly_name: "Bedroom Main Light" # switch configuration is in living_room_switches.yaml

switch:
  - platform: broadlink
    host: !secret bedroom_broadlink_rm_mini_ip
    mac: !secret bedroom_broadlink_rm_mini_mac
    timeout: 15
    type: rm_mini
