homeassistant:
  customize:
    switch.living_room_main_light:
      friendly_name: "Living Room Main Light"
    switch.living_room_small_light:
      friendly_name: "Living Room Small Light"
    switch.entrance_light:
      friendly_name: "Entrance Light"
    group.living_room_switches:
      friendly_name: "Lights"

group:
  living_room_switches:
    name: living_room_switches
    entities:
      - light.tv_lights
      - light.living_room_night_light
      - switch.living_room_main_light
      - switch.living_room_small_light
      - switch.balcony_light
      - switch.entrance_light

switch:
  - platform: broadlink
    host: !secret living_room_broadlink_rm_pro_ip
    mac: !secret living_room_broadlink_rm_pro_mac
    timeout: 15
    switches: 
      living_room_ac_updown_shutter:
        command_on: "JgDYAAABKJcROhA6ExYRFhEXEhUSORI5EhUSFRMVEzkRFRIVEhUSORIVExQVFBMUExQUOBI4FDgTFBIUFDgSFBQUFBQUExQUFBQTFBMUFBQTFBQ3EjgUFBQUFBQTFBQTFBQTFBQUExQUFBMUFBMUFBMUFDcSFBQUExQTFBMUExQTFBMUExQUFBIUFBQSFBQUExQTFBMUExQTFBQTExQUFBIUFDcTFBQUFBQUExQUExQUFBMUFBMUFBQTFDgSFBMUExQTFBMUExUSOBQUFBQTFBQ4ERQUOBI5FgANBQ=="
        command_off: "JgDYAAABKpUTOBI3ExQTFBMUFRMUOBI4FDgTNxQ4EzgTFBQUFBQTOBIUFBQSFBQUEhQUOBI4FTgTNxMUFDcTFBQUEhQUFBIVExQTFBMUExQTFBQ4EjgTFBQUEhQUFBIUFBQTFBMUExQUExMUFBMTFBQTEzgUFBQUFBQTFBMUFBQTFBQTFBQTFRMUExQUFBMUFBMUFBMUFBQTFBQUExQUExMUEzgVExIVEhQUFBQVExQTFBQUExQUFBMUFDcSFBQUEhQUFBMUExQTOBMUFRMUOBI4ExQUOBI4FgANBQ=="
      living_room_ac_sides_shutter:
        command_on: "JgDYAAABKZYROg87EBYRFhEWEhYSOg87EToROhI5EjkTFRMVEhUTORIUExQTFBMUExQTFBMUFBQSFBQ4EjgVFBMUFBMUFBMVExQTFBQUExQUExQ4EjgTFBQUFBQTFBQUExQUExQUExUTFBMUFBQTFBQTFDgSFBMUExQUExMUFBQSFBQUEhQUFBMUExQTFBMUExQTFBMUFBQSFBQUEhQUFBMTFDgTExQUFRMUFBMUFBQTFBQTFBQTFBQ4EjgTFBQUFBQTFBQTFBQUNxI4FBQUOBI4EzgTOBM4FgANBQ=="
        command_off: "JgDYAAABKJcSORA6ERYRFhIXERYROhA6EjoQOhI6EDoSFhIWExUROhEVExURFRMVERUTORE5FDkSFBI5EzgSFRQUEhQUFBIVExQTFBMUExQTFBM4EzgTFBQUEhQUFBMUExQTFBMUExQUExMUFBQSFBQUEjgUFBQUFBQTFBMUFBQTFBMUFBQTFRMUExQUFBMUExQUFBMUFBQTFBQUExQTFBQUEzgSFBQUEhUTFBIVExQTFBMUExQTFBM4FDcTFBQUEhQUFBIUFBQTOBM4ExQTOBM4FBQUOBM4FwANBQ=="
      living_room_ac_panel_light:
        command_on: "JgDYAAABKpUSOBI4FRMUFBMUFBMUOBI4ExQTFBQUFDgRFBQUExQTOBMUExQVNxIUFBQSFBQUExQTOBMUExQVExQUExQUFBMUFBQTFBQTFBQTFBQ4ETgUFBUTFBQTFBQUExQTFBQUExQUFBMUFBQTFBMUFDgSFBMUExQUExMUFBMTFBQUEhQVFBIUEhQTFBMUFRMUFBMUFBQUExQUExQUExQUEzgSFBQUExQTFBMUExQTFBMUExQTFBM4FBMVOBIUEzgTFBMUFBUTOBIUEzgUFBMUFBMUFBMUFgANBQ=="
        command_off: "JgDYAAABKpUSOBI4FRMUFBMUFBMUOBI4ExQTFBQUFDgRFBQUExQTOBMUExQVNxIUFBQSFBQUExQTOBMUExQVExQUExQUFBMUFBQTFBQTFBQTFBQ4ETgUFBUTFBQTFBQUExQTFBQUExQUFBMUFBQTFBMUFDgSFBMUExQUExMUFBMTFBQUEhQVFBIUEhQTFBMUFRMUFBMUFBQUExQUExQUExQUEzgSFBQUExQTFBMUExQTFBMUExQTFBM4FBMVOBIUEzgTFBMUFBUTOBIUEzgUFBMUFBMUFBMUFgANBQ=="
      living_room_main_light: 
        command_on: "6QpCAN8JFgkJFgkWFgkWCQkWFgkWCQkWFgkJFgkWFgkWCRYJCRYWCQkWCRYWCRYJCRYWCRYJCRYJ FhYJCRYJFhYJCRYJFg=="
        command_off: "6QpCAN8JCRYJFgkWFgkJFgkWFgkJFhYJFgkWCQkWFgkWCRYJFgkJFgkWCRYWCQkWCRYWCRYJFgkW CRYJCRYJFgkWCRYJFg=="
      living_room_small_light: 
        command_on: "6QpCAN8JFgkJFgkWCRYJFhYJCRYWCRYJCRYWCQkWCRYJFhYJFgkJFgkWCRYJFhYJFgkWCQkWCRYW CRYJCRYWCQkWFgkWCQ=="
        command_off: "6QpCAN8JCRYJFgkWCRYJFgkWFgkWCRYJCRYJFhYJFgkWCQkWFgkWCRYJCRYWCRYJCRYWCRYJCRYJ FhYJCRYWCQkWFgkJFg=="
      kitchen_main_light_fixed: 
        command_on: "6QpCAN8JCRYJFhYJCRYJFgkWFgkJFhYJCRYWCQkWFgkWCQkWCRYWCRYJCRYJFgkWFgkJFgkWCRYJFhYJFgkWCQkWCRYWCQ=="
        command_off: "6QpCAN8JCRYWCRYJCRYJFgkWFgkWCRYJFgkJFgkWCRYJFhYJFgkJFhYJFgkWCQkWFgkJFhYJFgkWCRYJCRYWCRYJCRYJFg=="
      kitchen_island_light_fixed: 
        command_on: "6QpCAN8JFgkWCQkWFgkJFhYJFgkWCQkWCRYWCRYJCRYJFhYJFgkWCQkWFgkWCRYJCRYWCQkWCRYJFhYJCRYWCQkWCRYJFg=="
        command_off: "6QpCAN8JCRYJFhYJCRYJFgkWCRYWCQkWFgkWCRYJFgkWCQkWFgkWCQkWCRYWCQkWCRYJFgkWFgkWCQkWFgkJFgkWFgkJFg=="
      main_hallway_light_fixed: 
        command_on: "6QpCAN8JFgkWCRYJFgkJFgkWCRYJFhYJFgkWCQkWCRYWCRYJCRYJFhYJFgkWCQkWCRYWCQkWCRYJFhYJCRYJFgkWFgkWCQ=="
        command_off: "6QpCAN8JFgkWCRYJCRYWCQkWFgkJFhYJFgkWCQkWFgkJFgkWFgkJFhYJCRYJFhYJFgkWCQkWCRYJFgkWCRYJFhYJFgkJFg=="
      small_bathroom_light_fixed:
        command_on: "6QpCAN8JFgkJFhYJFgkWCRYJFgkJFhYJCRYJFgkWFgkJFhYJFgkJFgkWFgkJFhYJCRYWCQkWCRYWCQkWCRYJFhYJCRYWCQ=="
        command_off: "6QpCAN8JFgkJFgkWCRYWCQkWCRYWCRYJCRYJFgkWFgkWCRYJCRYJFgkWFgkWCRYJCRYWCQkWCRYWCRYJFgkWCQkWFgkJFg=="
      shower_light:
        command_on: "6QpCAN8JCRYJFgkWFgkWCRYJCRYJFgkWFgkWCRYJCRYWCRYJFgkWCQkWFgkJFhYJFgkJFgkWFgkWCQkWFgkWCQkWFgkJFg=="
        command_off: "6QpCAN8JFgkWCRYJCRYWCQkWFgkWCQkWCRYWCRYJCRYWCQkWCRYWCQkWCRYJFgkWCRYJFhYJCRYJFhYJCRYJFgkWCRYWCQ=="
      closet_room_light:
        command_on: "6QpCAN8JFgkWCQkWFgkWCQkWFgkJFhYJCRYJFgkWCRYJFgkWCRYJFgkWCRYWCQkWFgkWCRYJCRYJFhYJCRYJFgkWFgkJFg=="
        command_off: "6QpCAN8JCRYWCRYJFgkWCQkWFgkJFhYJCRYJFhYJFgkWCRYJCRYWCRYJCRYWCRYJFgkWCRYJCRYWCQkWCRYWCQkWFgkWCQ=="
      bedroom_main_light:
        command_on: "6QpCAN8JFgkJFhYJCRYWCQkWCRYJFgkWCRYWCQkWFgkJFhYJFgkJFhYJFgkWCRYJFgkWCRYJFgkWCRYJCRYJFhYJFgkWCQ=="
        command_off: "6QpCAN8JCRYWCRYJFgkWCQkWCRYWCQkWFgkJFgkWFgkJFhYJFgkWCQkWFgkJFhYJFgkWCQkWFgkJFhYJCRYJFhYJFgkWCQ=="
      guest_room_light:
        command_on: "6QpCAN8JCRYWCQkWCRYJFhYJFgkJFhYJCRYJFgkWFgkWCQkWCRYWCRYJCRYWCQkWFgkJFhYJCRYWCRYJFgkWCRYJCRYJFg=="
        command_off: "6QpCAN8JCRYWCRYJFgkWCRYJCRYJFhYJCRYWCQkWFgkJFhYJFgkJFhYJFgkJFgkWCRYJFgkWFgkJFgkWFgkWCQkWCRYJFg=="
      balcony_light:
        command_on: "6QpCAN8JCRYWCRYJCRYWCQkWCRYJFgkWCRYWCRYJFgkJFgkWCRYJFhYJCRYWCQkWCRYWCRYJCRYJFhYJFgkWCRYJFgkWCQ=="
        command_off: "6QpCAN8JFgkJFhYJCRYWCQkWFgkJFhYJFgkJFhYJCRYWCQkWCRYWCQkWCRYWCQkWFgkJFhYJFgkJFgkWFgkJFhYJCRYJFg=="
      entrance_light:
        command_on: "6QpCAN8JFgkWCQkWFgkWCQkWCRYJFgkWFgkJFgkWCRYWCRYJCRYJFgkWFgkJFhYJFgkWCRYJFgkJFgkWCRYWCRYJFgkJFg=="
        command_off: "6QpCAN8JCRYWCQkWFgkWCRYJCRYWCQkWFgkWCQkWCRYWCQkWFgkWCRYJCRYJFhYJFgkWCQkWFgkWCQkWCRYWCQkWFgkWCQ=="
      main_bathroom_light:
        command_on: "6QpCAN8JCRYJFgkWFgkJFhYJFgkJFgkWFgkJFhYJCRYWCRYJCRYWCQkWCRYWCQkWCRYJFgkWFgkWCQkWFgkWCQkWFgkWCQ=="
        command_off: "6QpCAN8JFgkJFgkWFgkWCRYJCRYJFgkWCRYJFgkWCRYJFhYJCRYWCQkWCRYJFhYJFgkJFhYJCRYWCQkWFgkJFhYJCRYJFg=="
      small_hallway_light:
        command_on: "6QpCAN8JFgkWCQkWFgkWCQkWCRYJFgkWFgkJFgkWFgkJFgkWCRYJFhYJCRYWCQkWCRYWCRYJFgkWCRYJCRYWCRYJFgkWCQ=="
        command_off: "6QpCAN8JCRYJFgkWFgkWCRYJCRYJFhYJCRYWCRYJFgkJFgkWFgkWCQkWFgkWCRYJFgkJFhYJCRYWCQkWCRYWCQkWCRYWCQ=="
      office_light:
        command_on: "6QpCAN8JCRYWCRYJCRYJFgkWCRYWCRYJCRYWCRYJFgkJFhYJCRYWCQkWCRYWCRYJFgkWCRYJCRYJFhYJFgkWCQkWFgkWCQ==" #"6QpCAN8JFgkJFhYJCRYWCRYJCRYJFhYJFgkJFhYJCRYWCRYJFgkJFgkWCRYJFgkWFgkWCRYJCRYJFgkWCRYJFgkWCRYJFg=="
        command_off: "6QpCAN8JCRYWCQkWFgkJFgkWFgkWCQkWFgkJFhYJFgkJFgkWCRYWCQkWCRYWCQkWFgkWCQkWFgkJFhYJFgkJFgkWFgkJFg==" #"6QpCAN8JCRYWCQkWFgkWCRYJFgkJFgkWFgkWCRYJCRYJFhYJCRYWCQkWCRYJFgkWCRYJFhYJFgkJFgkWFgkJFgkWFgkJFg=="