homeassistant:
  customize:
    switch.shower_light:
      friendly_name: "Shower Light"
    switch.closet_room_light:
      friendly_name: "Closet Room Light"
    switch.bedroom_main_light:
      friendly_name: "Bedroom Main Light"
    group.bedroom_switches:
      friendly_name: "Lights"
      
group:
  bedroom_switches:
    name: bedroom_switches
    entities:
      - switch.closet_room_light
      - switch.shower_light
      - switch.bedroom_main_light
      
switch:
  - platform: broadlink
    host: !secret bedroom_broadlink_rm_mini_ip
    mac: !secret bedroom_broadlink_rm_mini_mac
    timeout: 15
    type: rm_mini
    switches:
      bedroom_ac_light:
        command_on: "JgDKAI6SEDcQExE2EDYRExA3EBMQNhISETYQExMREDYRExA2ERMQNhE2ETYQNhISEDcQExA3EBMREhETEBMRNhATETYQExE2EBMRNhESERMQNhETEDYRExA3EBMQNxE1ERMQNhETEqqPkRE2ERMQNhE2EBMRNhATEzQREhE2ERMQExA3EBMRNhATEjUQNhE2ETYREhE2ERIRNhIRERMREhISETURExA2ERMRNRETETUSEg8UFTIQExE2ERITNBESEjURNhATETYSEREADQUAAAAAAAAAAAAAAAAAAA=="
        command_off: "JgDKAI6SEDcQExE2EDYRExA3EBMQNhISETYQExMREDYRExA2ERMQNhE2ETYQNhISEDcQExA3EBMREhETEBMRNhATETYQExE2EBMRNhESERMQNhETEDYRExA3EBMQNxE1ERMQNhETEqqPkRE2ERMQNhE2EBMRNhATEzQREhE2ERMQExA3EBMRNhATEjUQNhE2ETYREhE2ERIRNhIRERMREhISETURExA2ERMRNRETETUSEg8UFTIQExE2ERITNBESEjURNhATETYSEREADQUAAAAAAAAAAAAAAAAAAA=="
      bedroom_ac_shutter:
        command_on: "JgDKAI+SEjQTERI0EzQTERIREzQSERMQEzQTEBMREjQTNBMREjQTERI0EzQTEBM0ExATNBM0EjUSERIREjUSERI1EhIREhE0EzUSNRIREhIREhIREhIQExIREhIQNhI1EjURNhA2EayOkhE2EBMRNhA2ERMQExE2EBMSEhI0ExESERI1EjUTEBI1ExATMxM0ExESNBMREjUSMxQ0EhETERI0ExESNRIREhETNBI1EjQTERIREhETERIRExESERIREzQSNRI0EzQTNBIADQUAAAAAAAAAAAAAAAAAAA=="
        command_off: "JgDKAI+SEjQTERI0EzQTERIREzQSERMQEzQTEBMREjQTNBMREjQTERI0EzQTEBM0ExATNBM0EjUSERIREjUSERI1EhIREhE0EzUSNRIREhIREhIREhIQExIREhIQNhI1EjURNhA2EayOkhE2EBMRNhA2ERMQExE2EBMSEhI0ExESERI1EjUTEBI1ExATMxM0ExESNBMREjUSMxQ0EhETERI0ExESNRIREhETNBI1EjQTERIREhETERIRExESERIREzQSNRI0EzQTNBIADQUAAAAAAAAAAAAAAAAAAA=="