homeassistant:
  customize:
    sensor.switcher_v2_nmap_tracker:
      friendly_name: "Switcher Water Heater"
      icon: mdi:steam
  customize_glob:
    "*.turn_on_boiler_*":
      hidden: true

sensor:
  - platform: template
    sensors:
      switcher_v2_nmap_tracker:
        value_template: "{%if states.device_tracker.switcher_v2.state == 'home'%}Online{%else%}Offline{%endif%}"

switcher_aio:
  phone_id: !secret switcher_phone_id
  device_id: !secret switcher_device_id
  device_password: !secret switcher_device_password

scene:
  - name: turn_on_boiler_15_min
    entities:
      script.turn_on_boiler_15_min:
        state: on
        
  - name: turn_on_boiler_30_min
    entities:
      script.turn_on_boiler_30_min:
        state: on
        
  - name: turn_on_boiler_45_min
    entities:
      script.turn_on_boiler_45_min:
        state: on
        
  - name: turn_on_boiler_60_min
    entities:
      script.turn_on_boiler_60_min:
        state: on
        
  - name: turn_on_boiler_1_h
    entities:
      script.turn_on_boiler_60_min:
        state: on
    
script:
  turn_on_boiler_15_min:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: switcher_aio.timer_minutes_input_select
          option: "15"
      - service: script.turn_on
        data:
          entity_id: switcher_aio.turn_on_timer_script
          
  turn_on_boiler_30_min:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: switcher_aio.timer_minutes_input_select
          option: "30"
      - service: script.turn_on
        data:
          entity_id: switcher_aio.turn_on_timer_script
          
  turn_on_boiler_45_min:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: switcher_aio.timer_minutes_input_select
          option: "45"
      - service: script.turn_on
        data:
          entity_id: switcher_aio.turn_on_timer_script
          
  turn_on_boiler_60_min:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: switcher_aio.timer_minutes_input_select
          option: "60"
      - service: script.turn_on
        data:
          entity_id: switcher_aio.turn_on_timer_script
  
