homeassistant:
  customize_domain:
    date_notifier:
      hidden: true

date_notifier:
  ##########################################
  ########## One Time Reminders ############
  ##########################################
  rafis_memorial_date:
    name: rafis_memorial_date
    hour: 10
    day: !secret rafis_memorial_date_day
    month: !secret rafis_memorial_date_month
    year: !secret rafis_memorial_date_year
    message: "Dad's memorial"
    days_notice: 7
    notifier: "telegram_tomer_service"
    
  tzilas_memorial_date:
    name: tzilas_memorial_date
    hour: 10
    day: !secret tzilas_memorial_date_day
    month: !secret tzilas_memorial_date_month
    year: !secret tzilas_memorial_date_year
    message: "Mom's memorial"
    days_notice: 7
    notifier: "telegram_tomer_service"
  
  ##########################################
  ########### Yearly Reminders #############
  ##########################################
  darias_birthday:
    name: darias_birthday
    hour: 10
    day: !secret darias_birthday_day
    month: !secret darias_birthday_month
    message: "Daria's Birthday"
    days_notice: 7
    notifier: "everyone"
    countdown: true
  
  wedding_day:
    name: wedding_day
    hour: 10
    day: !secret wedding_day_day
    month: !secret wedding_day_month
    message: "Wedding day"
    days_notice: 7
    notifier: "everyone"
    countdown: true
    
  havas_birthday:
    name: havas_birthday
    hour: 10
    day: !secret havas_birthday_day
    month: !secret havas_birthday_month
    message: "Hava's birthday"
    days_notice: 7
    notifier: "telegram_tomer_service"
    countdown: true
    
  tomers_birthday:
    name: tomers_birthday
    hour: 10
    day: !secret tomers_birthday_day
    month: !secret tomers_birthday_month
    message: "Tomer's birthday"
    days_notice: 4
    notifier: "telegram_hava_service"
    countdown: true
  
  matans_birthday:
    name: matans_birthday
    hour: 10
    day: !secret matans_birthday_day
    month: !secret matans_birthday_month
    message: "Matan's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  gilis_birthday:
    name: gilis_birthday
    hour: 10
    day: !secret gilis_birthday_day
    month: !secret gilis_birthday_month
    message: "Gili's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  mayas_birthday:
    name: mayas_birthday
    hour: 10
    day: !secret mayas_birthday_day
    month: !secret mayas_birthday_month
    message: "Maya's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  shir_stav_birthday:
    name: shir_stav_birthday
    hour: 10
    day: !secret shir_stav_birthday_day
    month: !secret shir_stav_birthday_month
    message: "Shir and Stav birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  tzilas_birthday:
    name: tzilas_birthday
    hour: 10
    day: !secret tzilas_birthday_day
    month: !secret tzilas_birthday_month
    message: "Mom's birthday"
    days_notice: 2
    notifier: "telegram_tomer_service"
    
  rafis_birthday:
    name: rafis_birthday
    hour: 10
    day: !secret rafis_birthday_day
    month: !secret rafis_birthday_month
    message: "Dad's birthday"
    days_notice: 2
    notifier: "telegram_tomer_service"
    
  tzilas_passing_date:
    name: tzilas_passing_date
    hour: 10
    day: !secret tzilas_passing_date_day
    month: !secret tzilas_passing_date_month
    message: "Mom's passing jewish date is the 25 of Elul 28/09/2016, please set a new reminder with the gregorian date for the memorial"
    days_notice: 0
    notifier: "telegram_tomer_service"
    
  rafis_passing_date:
    name: rafis_passing_date
    hour: 10
    day: !secret rafis_passing_date_day
    month: !secret rafis_passing_date_month
    message: "Dad's passing jewish date is the 16 of Adar 16/02/2014, please set a new reminder with the gregorian date for the memorial"
    days_notice: 0
    notifier: "telegram_tomer_service"
  
  avner_birthday:
    name: avner_birthday
    hour: 10
    day: !secret avner_birthday_day
    month: !secret avner_birthday_month
    message: "Avner's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  hana_birthday:
    name: hana_birthday
    hour: 10
    day: !secret hana_birthday_day
    month: !secret hana_birthday_month
    message: "Hana's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  dganit_birthday:
    name: dganit_birthday
    hour: 10
    day: !secret dganit_birthday_day
    month: !secret dganit_birthday_month
    message: "Dganit's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  yossi_birthday:
    name: yossi_birthday
    hour: 10
    day: !secret yossi_birthday_day
    month: !secret yossi_birthday_month
    message: "Yossi's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  sharon_birthday:
    name: sharon_birthday
    hour: 10
    day: !secret sharon_birthday_day
    month: !secret sharon_birthday_month
    message: "Sharon's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  menachem_birthday:
    name: menachem_birthday
    hour: 10
    day: !secret menachem_birthday_day
    month: !secret menachem_birthday_month
    message: "Menachem's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  daniel_birthday:
    name: daniel_birthday
    hour: 10
    day: !secret daniel_birthday_day
    month: !secret daniel_birthday_month
    message: "Daniels's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  liel_birthday:
    name: liel_birthday
    hour: 10
    day: !secret liel_birthday_day
    month: !secret liel_birthday_month
    message: "Liel's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  tuval_birthday:
    name: tuval_birthday
    hour: 10
    day: !secret tuval_birthday_day
    month: !secret tuval_birthday_month
    message: "Tuval's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  aviv_birthday:
    name: aviv_birthday
    hour: 10
    day: !secret aviv_birthday_day
    month: !secret aviv_birthday_month
    message: "Aviv's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
    
  shalev_birthday:
    name: shalev_birthday
    hour: 10
    day: !secret shalev_birthday_day
    month: !secret shalev_birthday_month
    message: "Shalev's birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true
  
  roy_sean_birthday:
    name: roy_sean_birthday
    hour: 10
    day: !secret roy_sean_birthday_day
    month: !secret roy_sean_birthday_month
    message: "Roy and Sean birthday"
    days_notice: 2
    notifier: "everyone"
    countdown: true

  ##########################################
  ########## Monthly Reminders #############
  ##########################################
  # Monthly Reminder will be send on the 19th of every month at 21:27
  #monthly_reminder:
  #  name: "montly test"
  #  hour: 21
  #  minute: 27
  #  day: 19
  #  message: "montly test2"
  #  days_notice: 0
  #  notifier: "telegram_tomer_service"
  
  ##########################################
  ########### Daily Reminders ##############
  ########################################## 
  # Daily Reminder will be send every day at 21:28
  #daily_reminder:
  #  name: "daily test"
  #  hour: 21
  #  minute: 28
  #  message: "daily test"
  #  notifier: "telegram_tomer_service"