homeassistant:
  customize:
    group.nmap_pa_trackers:
      friendly_name: "Personal Assistants"
      icon: mdi:assistant
      control: hidden
    group.nmap_remotes_trackers:
      friendly_name: "Remotes"
      icon: mdi:remote
      control: hidden
    group.nmap_yes_stb_trackers:
      friendly_name: "Yes STB's"
      icon: mdi:movie
      control: hidden
    group.nmap_computers_tracker:
      friendly_name: "Computers, Streamers & Consoles"
      icon: mdi:desktop-classic
      control: hidden
    group.nmap_diy_tracker:
      friendly_name: "DIY Stuff"
      icon: mdi:developer-board
      control: hidden
    group.nmap_lights_tracker:
      friendly_name: "Lights"
      icon: mdi:lightbulb
      control: hidden
    group.nmap_various_trackers:
      friendly_name: "Various Devices"
      icon: mdi:developer-board
      control: hidden
    group.nmap_phones_tracker:
      friendly_name: "Phones"
      icon: mdi:cellphone
      control: hidden
    sensor.dash_wand_nmap_tracker:
      friendly_name: "Dash Wand"
      icon: mdi:amazon
    sensor.tomers_laptop_nmap_tracker:
      friendly_name: "Tomer's Laptop"
      icon: mdi:windows
    sensor.havas_laptop_nmap_tracker:
      friendly_name: "Hava's Laptop"
      icon: mdi:windows
    sensor.tomers_phone_nmap_tracker:
      friendly_name: "Tomer's Phone"
      icon: mdi:cellphone-android
    sensor.havas_phone_nmap_tracker:
      friendly_name: "Hava's Phone"
      icon: mdi:cellphone-android
    sensor.switcher_v2_nmap_tracker:
      friendly_name: "Switcher Water Heater"
      icon: mdi:steam
    sensor.bedroom_rm_mini_nmap_tracker:
      friendly_name: "Bedroom RM Mini"
      icon: mdi:remote
    sensor.bedroom_msensor_nmap_tracker:
      friendly_name: "Bedroom Multi-Sensor"
      icon: mdi:developer-board
    sensor.bedroom_echo_nmap_tracker:
      friendly_name: "Bedroom Echo"
      icon: mdi:amazon
    sensor.bedroom_yes_nmap_tracker:
      friendly_name: "Bedroom Yes"
      icon: mdi:television-classic
    sensor.guest_room_yes_nmap_tracker:
      friendly_name: "Guest Room Yes"
      icon: mdi:television-classic
    sensor.kitchen_fire_8_tablet_nmap_tracker:
      friendly_name: "Kitchen Fire 8"
      icon: mdi:amazon
    sensor.kitchen_bar_sp2_nmap_tracker:
      friendly_name: "Kitchen Bar SP2"
      icon: mdi:power-socket-eu
    sensor.kitchen_echo_one_nmap_tracker:
      friendly_name: "Kitchen Echo"
      icon: mdi:amazon
    sensor.tv_lifxz_led_nmap_tracker:
      friendly_name: "Living Room Lifx Strip"
      icon: mdi:led-strip
    sensor.hue_bridge_nmap_tracker:
      friendly_name: "Living Room Hue Bridge"
      icon: mdi:lighthouse
    sensor.living_room_rm_pro_nmap_tracker:
      friendly_name: "Living Room RM Pro"
      icon: mdi:remote
    sensor.living_room_dot_nmap_tracker:
      friendly_name: "Living Room Dot"
      icon: mdi:amazon
    sensor.living_room_ghome_mini_nmap_tracker:
      friendly_name: "Living Room G-Home Mini"
      icon: mdi:google-assistant
    sensor.living_room_harmony_hub_nmap_tracker:
      friendly_name: "Living Room Harmony Hub"
      icon: mdi:remote
    sensor.living_room_samsung_tv_nmap_tracker:
      friendly_name: "Living Room Samsung TV"
      icon: mdi:television
    sensor.living_room_yes_nmap_tracker:
      friendly_name: "Living Room Yes"
      icon: mdi:television-classic
    sensor.shield_console_nmap_tracker:
      friendly_name: "Shield Console"
      icon: mdi:android
    sensor.nursery_dot_nmap_tracker:
      friendly_name: "Nursery Dot"
      icon: mdi:amazon
    sensor.nursery_fire_8_tablet_nmap_tracker:
      friendly_name: "Nursery Fire 8"
      icon: mdi:amazon
    sensor.nursery_broadlink_a1_nmap_tracker:
      friendly_name: "Nursery A1"
    sensor.home_workstation_nmap_tracker:
      friendly_name: "Home Workstation"
      icon: mdi:windows
    sensor.office_rm_mini_nmap_tracker:
      friendly_name: "Office RM Mini"
      icon: mdi:remote
    sensor.office_netgear_hub5_nmap_tracker:
      friendly_name: "Office Netgear 5 Port Hub"
      icon: mdi:access-point-network
    sensor.office_msensor_nmap_tracker:
      friendly_name: "Office Multi-Sensor"
      icon: mdi:developer-board
    sensor.xbox_360_nmap_tracker:
      friendly_name: "Xbox 360"
      icon: mdi:xbox
    sensor.office_dot_nmap_tracker:
      friendly_name: "Office Dot"
      icon: mdi:amazon
    sensor.office_chromecast_nmap_tracker:
      friendly_name: "Office Chromecast"
      icon: mdi:google-chrome
    sensor.service_room_s1c_nmap_tracker:
      friendly_name: "Service Room SC1"
      icon: mdi:power-socket-eu

    
    

device_tracker:
  - platform: nmap_tracker
    home_interval: 10
    consider_home: 0
    scan_options: -Pn --host-timeout 5s
    track_new_devices: false
    hosts:
      - !secret home_workstation_ip
      - !secret living_room_shield_ip
      - !secret guest_room_yes_ip
      - !secret bedroom_yes_ip
      - !secret living_room_yes_ip
      - !secret office_netgear_switch5_ip
      - !secret switcher_ip
      - !secret office_echo_dot_ip
      - !secret kitchen_echo_one_ip
      - !secret bedroom_echo_one_ip
      - !secret nursery_broadlink_a1_ip
      - !secret kitchen_bar_light_broadlink_sp2_ip
      - !secret service_room_light_broadlink_sc1_ip
      - !secret bedroom_broadlink_rm_mini_ip
      - !secret living_room_broadlink_rm_pro_ip
      - !secret living_room_samaung_tv_ip
      - !secret living_room_tv_lifx_z_ip
      - !secret living_room_logitech_harmony_hub_ip
      - !secret tomer_phone_ip
      - !secret hava_phone_ip
      - !secret tomer_work_dell_ip
      - !secret hava_lenovo_ip
      - !secret dash_wand_ip
      - !secret living_room_ghome_mini_ip
      - !secret office_chromecast_ip
      - !secret office_broadlink_rm_mini_ip
      - !secret office_xbox_360_ip
      - !secret hallways_omg_ip
      - !secret office_multisensor_ip
      - !secret bedroom_multisensor_ip
      - !secret living_room_hue_bridge_ip
      - !secret nursery_fire8_ip
      - !secret living_room_echo_dot_ip
      - !secret nursery_echo_dot_ip
      - !secret kitchen_fire_8_ip

group:
  nmap_pa_trackers:
    name: nmap_pa_trackers
    entities:
      - sensor.kitchen_echo_one_nmap_tracker
      - sensor.living_room_dot_nmap_tracker
      - sensor.bedroom_echo_nmap_tracker
      - sensor.office_dot_nmap_tracker
      - sensor.nursery_dot_nmap_tracker
      - sensor.dash_wand_nmap_tracker
      - sensor.living_room_ghome_mini_nmap_tracker
  
  nmap_remotes_trackers:
    name: nmap_remote_trackers
    entities:
      - sensor.living_room_rm_pro_nmap_tracker
      - sensor.bedroom_rm_mini_nmap_tracker
      - sensor.office_rm_mini_nmap_tracker
      - sensor.living_room_harmony_hub_nmap_tracker
  
  nmap_yes_stb_trackers:
    name: nmap_yes_stb_trackers
    entities:
      - sensor.living_room_yes_nmap_tracker
      - sensor.bedroom_yes_nmap_tracker
      - sensor.guest_room_yes_nmap_tracker
  
  nmap_diy_tracker:
    name: nmap_diy_tracker
    entities:
      - sensor.hallway_rf_gw_nmap_tracker
      - sensor.office_msensor_nmap_tracker
      - sensor.bedroom_msensor_nmap_tracker
        
  nmap_computers_tracker:
    name: nmap_computers_tracker
    entities:
      - sensor.home_workstation_nmap_tracker
      - sensor.shield_console_nmap_tracker
      - sensor.office_chromecast_nmap_tracker
      - sensor.xbox_360_nmap_tracker
      - sensor.tomers_laptop_nmap_tracker
      - sensor.havas_laptop_nmap_tracker
      - sensor.nursery_fire_8_tablet_nmap_tracker
      - sensor.kitchen_fire_8_tablet_nmap_tracker
  
  nmap_lights_tracker:
    name: nmap_lights_tracker
    entities:
      - sensor.kitchen_bar_sp2_nmap_tracker
      - sensor.tv_lifxz_led_nmap_tracker
      - sensor.service_room_s1c_nmap_tracker
      - sensor.hue_bridge_nmap_tracker
        
  nmap_various_trackers:
    name: nmap_trackers
    entities:
      - sensor.switcher_v2_nmap_tracker
      - sensor.office_netgear_hub5_nmap_tracker
      - sensor.nursery_broadlink_a1_nmap_tracker
      - sensor.living_room_samsung_tv_nmap_tracker
      - sensor.tomerfu
      - sensor.home_workstation_uptime_human
      
  nmap_phones_tracker:
    name: nmap_phones_tracker
    entities:
      - sensor.tomers_phone_nmap_tracker
      - sensor.havas_phone_nmap_tracker
  
sensor:
  - platform: template
    sensors:
      tomers_laptop_nmap_tracker:
        value_template: "{%if states.device_tracker.tomers_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
      havas_laptop_nmap_tracker:
        value_template: "{%if states.device_tracker.havas_laptop.state == 'home'%}Online{%else%}Offline{%endif%}"
      dash_wand_nmap_tracker:
        value_template: "{%if states.device_tracker.dash_wand.state == 'home'%}Online{%else%}Offline{%endif%}"
      tomers_phone_nmap_tracker:
        value_template: "{%if states.device_tracker.tomers_phone.state == 'home'%}Online{%else%}Offline{%endif%}"
      havas_phone_nmap_tracker:
        value_template: "{%if states.device_tracker.havas_phone.state == 'home'%}Online{%else%}Offline{%endif%}"
      switcher_v2_nmap_tracker:
        value_template: "{%if states.device_tracker.switcher_v2.state == 'home'%}Online{%else%}Offline{%endif%}"
      bedroom_rm_mini_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_rm_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
      bedroom_msensor_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_sensorhomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
      bedroom_echo_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_echo.state == 'home'%}Online{%else%}Offline{%endif%}"
      bedroom_yes_nmap_tracker:
        value_template: "{%if states.device_tracker.bedroom_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
      guest_room_yes_nmap_tracker:
        value_template: "{%if states.device_tracker.guest_room_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
      kitchen_fire_8_tablet_nmap_tracker:
        value_template: "{%if states.device_tracker.kitchen_fire_8_tablet.state == 'home'%}Online{%else%}Offline{%endif%}"
      kitchen_bar_sp2_nmap_tracker:
        value_template: "{%if states.device_tracker.kitchen_bar_sp2.state == 'home'%}Online{%else%}Offline{%endif%}"
      kitchen_echo_one_nmap_tracker:
        value_template: "{%if states.device_tracker.kitchen_echo_one.state == 'home'%}Online{%else%}Offline{%endif%}"
      tv_lifxz_led_nmap_tracker:
        value_template: "{%if states.device_tracker.tv_lifxz_led.state == 'home'%}Online{%else%}Offline{%endif%}"
      hue_bridge_nmap_tracker:
        value_template: "{%if states.device_tracker.hue_bridgehomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_rm_pro_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_rm_pro.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_dot_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_dot.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_ghome_mini_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_ghome_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_harmony_hub_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_harmony_hub.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_samsung_tv_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_samsung_tv.state == 'home'%}Online{%else%}Offline{%endif%}"
      living_room_yes_nmap_tracker:
        value_template: "{%if states.device_tracker.living_room_yes.state == 'home'%}Online{%else%}Offline{%endif%}"
      shield_console_nmap_tracker:
        value_template: "{%if states.device_tracker.shield_console.state == 'home'%}Online{%else%}Offline{%endif%}"
      nursery_dot_nmap_tracker:
        value_template: "{%if states.device_tracker.nursery_echo_dot == 'home'%}Online{%else%}Offline{%endif%}"
      nursery_fire_8_tablet_nmap_tracker:
        value_template: "{%if states.device_tracker.nursery_fire_8_tablet.state == 'home'%}Online{%else%}Offline{%endif%}"
      nursery_broadlink_a1_nmap_tracker:
        value_template: "{%if states.device_tracker.nursery_broadlink_a1.state == 'home'%}Online{%else%}Offline{%endif%}"
      home_workstation_nmap_tracker:
        value_template: "{%if states.device_tracker.home_workstation.state == 'home'%}Online{%else%}Offline{%endif%}"
      office_netgear_hub5_nmap_tracker:
        value_template: "{%if states.device_tracker.office_netgear_hub5.state == 'home'%}Online{%else%}Offline{%endif%}"
      office_chromecast_nmap_tracker:
        value_template: "{%if states.device_tracker.office_chromecast.state == 'home'%}Online{%else%}Offline{%endif%}"
      xbox_360_nmap_tracker:
        value_template: "{%if states.device_tracker.xbox_360.state == 'home'%}Online{%else%}Offline{%endif%}"
      office_dot_nmap_tracker:
        value_template: "{%if states.device_tracker.office_dot.state == 'home'%}Online{%else%}Offline{%endif%}"
      office_rm_mini_nmap_tracker:
        value_template: "{%if states.device_tracker.office_rm_mini.state == 'home'%}Online{%else%}Offline{%endif%}"
      office_msensor_nmap_tracker:
        value_template: "{%if states.device_tracker.office_sensorhomeserverlocal.state == 'home'%}Online{%else%}Offline{%endif%}"
      service_room_s1c_nmap_tracker:
        value_template: "{%if states.device_tracker.service_room_s1c.state == 'home'%}Online{%else%}Offline{%endif%}"
