homeassistant:
  customize:
    sensor.homenas_status:
      friendly_name: "Status"
    sensor.homenas_system_temperature:
      friendly_name: "System Temperature"
    sensor.homenas_cpu_usage:
      friendly_name: "CPU Usage"
    sensor.homenas_cpu_temperature:
      friendly_name: "CPU Temperature"
    sensor.homenas_memory_usage:
      friendly_name: "Memory Usage"
    sensor.homenas_memory_available:
      friendly_name: "Memory Available"
    sensor.homenas_memory_used:
      friendly_name: "Memory Used"
    sensor.homenas_network_link_eth0:
      friendly_name: "Network Link (eth0)"
    sensor.homenas_network_down_eth0:
      friendly_name: "Network Down (eth0)"
    sensor.homenas_network_up_eth0:
      friendly_name: "Netword Up (eth0)"
    sensor.homenas_smart_status_drive_01:
      friendly_name: "SMART Status (Drive 0:1)"
    sensor.homenas_temperature_drive_01:
      friendly_name: "Temperature (Drive 0:1)"
    sensor.homenas_volume_used_datavol1:
      friendly_name: "Volume Used (DataVol1)"
    sensor.homenas_free_space_datavol1:
      friendly_name: "Free Space (DataVol1)"
    sensor.homenas_used_space_datavol1:
      friendly_name: "Used Space (DataVol1)"
    sensor.qnap_homenas_uptime:
      friendly_name: "Uptime"
      icon: mdi:timelapse
    group.qnap_homenas_group:
      friendly_name: "Home NAS"

group:
  qnap_homenas_group:
    name: qnap_homenas_group
    entities:
      - sensor.homenas_status
      - sensor.qnap_homenas_uptime
      - sensor.homenas_system_temperature
      - sensor.homenas_cpu_usage
      - sensor.homenas_cpu_temperature
      - sensor.homenas_memory_usage
      - sensor.homenas_memory_available
      - sensor.homenas_memory_used
      - sensor.homenas_network_link_eth0
      - sensor.homenas_network_down_eth0
      - sensor.homenas_network_up_eth0
      - sensor.homenas_smart_status_drive_01
      - sensor.homenas_temperature_drive_01
      - sensor.homenas_volume_used_datavol1
      - sensor.homenas_free_space_datavol1
      - sensor.homenas_used_space_datavol1

sensor:
  - platform: template
    sensors:
      qnap_homenas_uptime:
        value_template: "{{ states.sensor.homenas_status.attributes.Uptime }}"
        
  - platform: qnap
    host: !secret qnap_ip
    port: !secret qnap_port
    username: !secret qnap_user
    password: !secret qnap_password
    ssl: false
    verify_ssl: false
    timeout: 30
    drives:
      - 0:1
    volumes:
      - DataVol1
    nics:
      - eth0
    monitored_conditions:
      - status
      - system_temp
      - cpu_temp
      - cpu_usage
      - memory_free
      - memory_used
      - memory_percent_used
      - network_link_status
      - network_tx
      - network_rx
      - drive_smart_status
      - drive_temp
      - volume_size_free
      - volume_size_used
      - volume_percentage_used
